/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Purchase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Purchase{}

// Purchase Purchase details for fraud checks; core fields are common, instrument specifics live in `paymentMethod`. 
type Purchase struct {
	// Unique identifier for the location where the transaction occurred.
	LocationId *string `json:"locationId,omitempty" validate:"regexp=^[a-zA-Z0-9\\\\-_]{3,50}$"`
	DeviceInfo *DeviceInfo `json:"deviceInfo,omitempty"`
	// RFC 3339 timestamp with timezone.
	Timestamp *string `json:"timestamp,omitempty" validate:"regexp=^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(\\\\.\\\\d{1,9})?(Z|[+-]\\\\d{2}:\\\\d{2})$"`
	// A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens. 
	TransactionId *string `json:"transactionId,omitempty" validate:"regexp=^[a-zA-Z0-9\\\\-_]+$"`
	// Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
	Amount float32 `json:"amount"`
	// ISO 4217 currency code (e.g., 'USD').
	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
	Channel *ChannelEnum `json:"channel,omitempty"`
	EntryMethod *EntryMethodEnum `json:"entryMethod,omitempty"`
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	Order *OrderContext `json:"order,omitempty"`
	// List of discount codes applied to the purchase.
	Discounts []DiscountCode `json:"discounts,omitempty"`
	PayerType *PayerTypeEnum `json:"payerType,omitempty"`
	StoredCredential *StoredCredentialContext `json:"storedCredential,omitempty"`
	Merchant *MerchantContext `json:"merchant,omitempty"`
	// Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
	Metadata *string `json:"metadata,omitempty"`
}

type _Purchase Purchase

// NewPurchase instantiates a new Purchase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchase(amount float32, currency string, paymentMethod PaymentMethod) *Purchase {
	this := Purchase{}
	this.Amount = amount
	this.Currency = currency
	this.PaymentMethod = paymentMethod
	var payerType PayerTypeEnum = PAYERTYPEENUM_CONSUMER
	this.PayerType = &payerType
	return &this
}

// NewPurchaseWithDefaults instantiates a new Purchase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseWithDefaults() *Purchase {
	this := Purchase{}
	var payerType PayerTypeEnum = PAYERTYPEENUM_CONSUMER
	this.PayerType = &payerType
	return &this
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *Purchase) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *Purchase) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *Purchase) SetLocationId(v string) {
	o.LocationId = &v
}

// GetDeviceInfo returns the DeviceInfo field value if set, zero value otherwise.
func (o *Purchase) GetDeviceInfo() DeviceInfo {
	if o == nil || IsNil(o.DeviceInfo) {
		var ret DeviceInfo
		return ret
	}
	return *o.DeviceInfo
}

// GetDeviceInfoOk returns a tuple with the DeviceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetDeviceInfoOk() (*DeviceInfo, bool) {
	if o == nil || IsNil(o.DeviceInfo) {
		return nil, false
	}
	return o.DeviceInfo, true
}

// HasDeviceInfo returns a boolean if a field has been set.
func (o *Purchase) HasDeviceInfo() bool {
	if o != nil && !IsNil(o.DeviceInfo) {
		return true
	}

	return false
}

// SetDeviceInfo gets a reference to the given DeviceInfo and assigns it to the DeviceInfo field.
func (o *Purchase) SetDeviceInfo(v DeviceInfo) {
	o.DeviceInfo = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *Purchase) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *Purchase) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *Purchase) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *Purchase) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *Purchase) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *Purchase) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetAmount returns the Amount field value
func (o *Purchase) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Purchase) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Purchase) SetAmount(v float32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *Purchase) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *Purchase) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *Purchase) SetCurrency(v string) {
	o.Currency = v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *Purchase) GetChannel() ChannelEnum {
	if o == nil || IsNil(o.Channel) {
		var ret ChannelEnum
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetChannelOk() (*ChannelEnum, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *Purchase) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given ChannelEnum and assigns it to the Channel field.
func (o *Purchase) SetChannel(v ChannelEnum) {
	o.Channel = &v
}

// GetEntryMethod returns the EntryMethod field value if set, zero value otherwise.
func (o *Purchase) GetEntryMethod() EntryMethodEnum {
	if o == nil || IsNil(o.EntryMethod) {
		var ret EntryMethodEnum
		return ret
	}
	return *o.EntryMethod
}

// GetEntryMethodOk returns a tuple with the EntryMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetEntryMethodOk() (*EntryMethodEnum, bool) {
	if o == nil || IsNil(o.EntryMethod) {
		return nil, false
	}
	return o.EntryMethod, true
}

// HasEntryMethod returns a boolean if a field has been set.
func (o *Purchase) HasEntryMethod() bool {
	if o != nil && !IsNil(o.EntryMethod) {
		return true
	}

	return false
}

// SetEntryMethod gets a reference to the given EntryMethodEnum and assigns it to the EntryMethod field.
func (o *Purchase) SetEntryMethod(v EntryMethodEnum) {
	o.EntryMethod = &v
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *Purchase) GetPaymentMethod() PaymentMethod {
	if o == nil {
		var ret PaymentMethod
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *Purchase) GetPaymentMethodOk() (*PaymentMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *Purchase) SetPaymentMethod(v PaymentMethod) {
	o.PaymentMethod = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *Purchase) GetOrder() OrderContext {
	if o == nil || IsNil(o.Order) {
		var ret OrderContext
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetOrderOk() (*OrderContext, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Purchase) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given OrderContext and assigns it to the Order field.
func (o *Purchase) SetOrder(v OrderContext) {
	o.Order = &v
}

// GetDiscounts returns the Discounts field value if set, zero value otherwise.
func (o *Purchase) GetDiscounts() []DiscountCode {
	if o == nil || IsNil(o.Discounts) {
		var ret []DiscountCode
		return ret
	}
	return o.Discounts
}

// GetDiscountsOk returns a tuple with the Discounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetDiscountsOk() ([]DiscountCode, bool) {
	if o == nil || IsNil(o.Discounts) {
		return nil, false
	}
	return o.Discounts, true
}

// HasDiscounts returns a boolean if a field has been set.
func (o *Purchase) HasDiscounts() bool {
	if o != nil && !IsNil(o.Discounts) {
		return true
	}

	return false
}

// SetDiscounts gets a reference to the given []DiscountCode and assigns it to the Discounts field.
func (o *Purchase) SetDiscounts(v []DiscountCode) {
	o.Discounts = v
}

// GetPayerType returns the PayerType field value if set, zero value otherwise.
func (o *Purchase) GetPayerType() PayerTypeEnum {
	if o == nil || IsNil(o.PayerType) {
		var ret PayerTypeEnum
		return ret
	}
	return *o.PayerType
}

// GetPayerTypeOk returns a tuple with the PayerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetPayerTypeOk() (*PayerTypeEnum, bool) {
	if o == nil || IsNil(o.PayerType) {
		return nil, false
	}
	return o.PayerType, true
}

// HasPayerType returns a boolean if a field has been set.
func (o *Purchase) HasPayerType() bool {
	if o != nil && !IsNil(o.PayerType) {
		return true
	}

	return false
}

// SetPayerType gets a reference to the given PayerTypeEnum and assigns it to the PayerType field.
func (o *Purchase) SetPayerType(v PayerTypeEnum) {
	o.PayerType = &v
}

// GetStoredCredential returns the StoredCredential field value if set, zero value otherwise.
func (o *Purchase) GetStoredCredential() StoredCredentialContext {
	if o == nil || IsNil(o.StoredCredential) {
		var ret StoredCredentialContext
		return ret
	}
	return *o.StoredCredential
}

// GetStoredCredentialOk returns a tuple with the StoredCredential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetStoredCredentialOk() (*StoredCredentialContext, bool) {
	if o == nil || IsNil(o.StoredCredential) {
		return nil, false
	}
	return o.StoredCredential, true
}

// HasStoredCredential returns a boolean if a field has been set.
func (o *Purchase) HasStoredCredential() bool {
	if o != nil && !IsNil(o.StoredCredential) {
		return true
	}

	return false
}

// SetStoredCredential gets a reference to the given StoredCredentialContext and assigns it to the StoredCredential field.
func (o *Purchase) SetStoredCredential(v StoredCredentialContext) {
	o.StoredCredential = &v
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *Purchase) GetMerchant() MerchantContext {
	if o == nil || IsNil(o.Merchant) {
		var ret MerchantContext
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetMerchantOk() (*MerchantContext, bool) {
	if o == nil || IsNil(o.Merchant) {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *Purchase) HasMerchant() bool {
	if o != nil && !IsNil(o.Merchant) {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given MerchantContext and assigns it to the Merchant field.
func (o *Purchase) SetMerchant(v MerchantContext) {
	o.Merchant = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Purchase) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchase) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Purchase) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *Purchase) SetMetadata(v string) {
	o.Metadata = &v
}

func (o Purchase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Purchase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	if !IsNil(o.DeviceInfo) {
		toSerialize["deviceInfo"] = o.DeviceInfo
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.EntryMethod) {
		toSerialize["entryMethod"] = o.EntryMethod
	}
	toSerialize["paymentMethod"] = o.PaymentMethod
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.Discounts) {
		toSerialize["discounts"] = o.Discounts
	}
	if !IsNil(o.PayerType) {
		toSerialize["payerType"] = o.PayerType
	}
	if !IsNil(o.StoredCredential) {
		toSerialize["storedCredential"] = o.StoredCredential
	}
	if !IsNil(o.Merchant) {
		toSerialize["merchant"] = o.Merchant
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *Purchase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"currency",
		"paymentMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPurchase := _Purchase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPurchase)

	if err != nil {
		return err
	}

	*o = Purchase(varPurchase)

	return err
}

type NullablePurchase struct {
	value *Purchase
	isSet bool
}

func (v NullablePurchase) Get() *Purchase {
	return v.value
}

func (v *NullablePurchase) Set(val *Purchase) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchase) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchase(val *Purchase) *NullablePurchase {
	return &NullablePurchase{value: val, isSet: true}
}

func (v NullablePurchase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


