/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.2
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentManifest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentManifest{}

// AgentManifest Proof of delegation for an autonomous shopping agent (UCP/MCP compatible).  Allows PayRisk to verify the \"Who\" and \"Trust\" behind a machine-driven transaction. 
type AgentManifest struct {
	Provider AgentProvider `json:"provider"`
	// Specific model version of the agent.
	Model string `json:"model"`
	// Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Supports \"ecid_\" slugs (Legacy) or \"cus_\" hex (Preferred). 
	PrincipalId string `json:"principalId" validate:"regexp=^(ecid_[a-z0-9\\\\-_]{2,96}|cus_[a-f0-9]{32})$"`
	// Platform-provided reputation score for the agent.
	TrustTier float32 `json:"trustTier"`
	// Authorized scope of authority for the agent.
	Capabilities []string `json:"capabilities,omitempty"`
}

type _AgentManifest AgentManifest

// NewAgentManifest instantiates a new AgentManifest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentManifest(provider AgentProvider, model string, principalId string, trustTier float32) *AgentManifest {
	this := AgentManifest{}
	this.Provider = provider
	this.Model = model
	this.PrincipalId = principalId
	this.TrustTier = trustTier
	return &this
}

// NewAgentManifestWithDefaults instantiates a new AgentManifest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentManifestWithDefaults() *AgentManifest {
	this := AgentManifest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *AgentManifest) GetProvider() AgentProvider {
	if o == nil {
		var ret AgentProvider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *AgentManifest) GetProviderOk() (*AgentProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *AgentManifest) SetProvider(v AgentProvider) {
	o.Provider = v
}

// GetModel returns the Model field value
func (o *AgentManifest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *AgentManifest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *AgentManifest) SetModel(v string) {
	o.Model = v
}

// GetPrincipalId returns the PrincipalId field value
func (o *AgentManifest) GetPrincipalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalId
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value
// and a boolean to check if the value has been set.
func (o *AgentManifest) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalId, true
}

// SetPrincipalId sets field value
func (o *AgentManifest) SetPrincipalId(v string) {
	o.PrincipalId = v
}

// GetTrustTier returns the TrustTier field value
func (o *AgentManifest) GetTrustTier() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TrustTier
}

// GetTrustTierOk returns a tuple with the TrustTier field value
// and a boolean to check if the value has been set.
func (o *AgentManifest) GetTrustTierOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrustTier, true
}

// SetTrustTier sets field value
func (o *AgentManifest) SetTrustTier(v float32) {
	o.TrustTier = v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *AgentManifest) GetCapabilities() []string {
	if o == nil || IsNil(o.Capabilities) {
		var ret []string
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentManifest) GetCapabilitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *AgentManifest) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []string and assigns it to the Capabilities field.
func (o *AgentManifest) SetCapabilities(v []string) {
	o.Capabilities = v
}

func (o AgentManifest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentManifest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["model"] = o.Model
	toSerialize["principalId"] = o.PrincipalId
	toSerialize["trustTier"] = o.TrustTier
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	return toSerialize, nil
}

func (o *AgentManifest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"model",
		"principalId",
		"trustTier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentManifest := _AgentManifest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentManifest)

	if err != nil {
		return err
	}

	*o = AgentManifest(varAgentManifest)

	return err
}

type NullableAgentManifest struct {
	value *AgentManifest
	isSet bool
}

func (v NullableAgentManifest) Get() *AgentManifest {
	return v.value
}

func (v *NullableAgentManifest) Set(val *AgentManifest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentManifest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentManifest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentManifest(val *AgentManifest) *NullableAgentManifest {
	return &NullableAgentManifest{value: val, isSet: true}
}

func (v NullableAgentManifest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentManifest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


