/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Crypto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Crypto{}

// Crypto struct for Crypto
type Crypto struct {
	// Fixed to `crypto` for this schema.
	Type string `json:"type"`
}

type _Crypto Crypto

// NewCrypto instantiates a new Crypto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrypto(type_ string) *Crypto {
	this := Crypto{}
	this.Type = type_
	return &this
}

// NewCryptoWithDefaults instantiates a new Crypto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoWithDefaults() *Crypto {
	this := Crypto{}
	return &this
}

// GetType returns the Type field value
func (o *Crypto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Crypto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Crypto) SetType(v string) {
	o.Type = v
}

func (o Crypto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Crypto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *Crypto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrypto := _Crypto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCrypto)

	if err != nil {
		return err
	}

	*o = Crypto(varCrypto)

	return err
}

type NullableCrypto struct {
	value *Crypto
	isSet bool
}

func (v NullableCrypto) Get() *Crypto {
	return v.value
}

func (v *NullableCrypto) Set(val *Crypto) {
	v.value = val
	v.isSet = true
}

func (v NullableCrypto) IsSet() bool {
	return v.isSet
}

func (v *NullableCrypto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrypto(val *Crypto) *NullableCrypto {
	return &NullableCrypto{value: val, isSet: true}
}

func (v NullableCrypto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrypto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


