/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.1
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PurchaseUsageEnum Payment use case.
type PurchaseUsageEnum string

// List of PurchaseUsageEnum
const (
	PURCHASEUSAGEENUM_ONE_TIME PurchaseUsageEnum = "one_time"
	PURCHASEUSAGEENUM_RECURRING PurchaseUsageEnum = "recurring"
	PURCHASEUSAGEENUM_INSTALLMENT PurchaseUsageEnum = "installment"
	PURCHASEUSAGEENUM_UNSCHEDULED PurchaseUsageEnum = "unscheduled"
)

// All allowed values of PurchaseUsageEnum enum
var AllowedPurchaseUsageEnumEnumValues = []PurchaseUsageEnum{
	"one_time",
	"recurring",
	"installment",
	"unscheduled",
}

func (v *PurchaseUsageEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PurchaseUsageEnum(value)
	for _, existing := range AllowedPurchaseUsageEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PurchaseUsageEnum", value)
}

// NewPurchaseUsageEnumFromValue returns a pointer to a valid PurchaseUsageEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPurchaseUsageEnumFromValue(v string) (*PurchaseUsageEnum, error) {
	ev := PurchaseUsageEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PurchaseUsageEnum: valid values are %v", v, AllowedPurchaseUsageEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PurchaseUsageEnum) IsValid() bool {
	for _, existing := range AllowedPurchaseUsageEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PurchaseUsageEnum value
func (v PurchaseUsageEnum) Ptr() *PurchaseUsageEnum {
	return &v
}

type NullablePurchaseUsageEnum struct {
	value *PurchaseUsageEnum
	isSet bool
}

func (v NullablePurchaseUsageEnum) Get() *PurchaseUsageEnum {
	return v.value
}

func (v *NullablePurchaseUsageEnum) Set(val *PurchaseUsageEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseUsageEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseUsageEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseUsageEnum(val *PurchaseUsageEnum) *NullablePurchaseUsageEnum {
	return &NullablePurchaseUsageEnum{value: val, isSet: true}
}

func (v NullablePurchaseUsageEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseUsageEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

