/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DecisionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecisionResponse{}

// DecisionResponse The synchronous risk decision for a purchase.
type DecisionResponse struct {
	// Universal decision identifier. For purchases, equals paymentIntentId.
	AssessmentId string `json:"assessmentId" validate:"regexp=^[a-zA-Z0-9_-]+$"`
	Decision string `json:"decision"`
	// RFC 3339 timestamp with timezone.
	DecisionAt string `json:"decisionAt" validate:"regexp=^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(\\\\.\\\\d{1,9})?(Z|[+-]\\\\d{2}:\\\\d{2})$"`
	// DEPRECATED: Use decisionScore instead. Current blended risk score.
	RiskScore float32 `json:"riskScore"`
	// The authoritative blended risk score (0.0 - 1.0) derived from expert fusion.
	DecisionScore float32 `json:"decisionScore"`
	FraudScore *FraudScore `json:"fraudScore,omitempty"`
	Breakdown *RiskBreakdown `json:"breakdown,omitempty"`
	// Technical reason codes for the decision.
	ReasonCodes []string `json:"reasonCodes,omitempty"`
	// Structured reason details for the decision.
	Reasons []ReasonDetail `json:"reasons,omitempty"`
	Actions []string `json:"actions,omitempty"`
	// Server-minted unique payment identifier.
	PaymentIntentId *string `json:"paymentIntentId,omitempty" validate:"regexp=^pi_[a-f0-9]{32}$"`
	// The version of the policy that generated the decision.
	PolicyVersion *string `json:"policyVersion,omitempty"`
	// The version of the model that generated the decision.
	ModelVersion *string `json:"modelVersion,omitempty"`
	// Time to live for the decision in seconds.
	TtlSeconds *int32 `json:"ttlSeconds,omitempty"`
}

type _DecisionResponse DecisionResponse

// NewDecisionResponse instantiates a new DecisionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecisionResponse(assessmentId string, decision string, decisionAt string, riskScore float32, decisionScore float32) *DecisionResponse {
	this := DecisionResponse{}
	this.AssessmentId = assessmentId
	this.Decision = decision
	this.DecisionAt = decisionAt
	this.RiskScore = riskScore
	this.DecisionScore = decisionScore
	return &this
}

// NewDecisionResponseWithDefaults instantiates a new DecisionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionResponseWithDefaults() *DecisionResponse {
	this := DecisionResponse{}
	return &this
}

// GetAssessmentId returns the AssessmentId field value
func (o *DecisionResponse) GetAssessmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssessmentId
}

// GetAssessmentIdOk returns a tuple with the AssessmentId field value
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetAssessmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssessmentId, true
}

// SetAssessmentId sets field value
func (o *DecisionResponse) SetAssessmentId(v string) {
	o.AssessmentId = v
}

// GetDecision returns the Decision field value
func (o *DecisionResponse) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *DecisionResponse) SetDecision(v string) {
	o.Decision = v
}

// GetDecisionAt returns the DecisionAt field value
func (o *DecisionResponse) GetDecisionAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DecisionAt
}

// GetDecisionAtOk returns a tuple with the DecisionAt field value
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetDecisionAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DecisionAt, true
}

// SetDecisionAt sets field value
func (o *DecisionResponse) SetDecisionAt(v string) {
	o.DecisionAt = v
}

// GetRiskScore returns the RiskScore field value
func (o *DecisionResponse) GetRiskScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field value
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskScore, true
}

// SetRiskScore sets field value
func (o *DecisionResponse) SetRiskScore(v float32) {
	o.RiskScore = v
}

// GetDecisionScore returns the DecisionScore field value
func (o *DecisionResponse) GetDecisionScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DecisionScore
}

// GetDecisionScoreOk returns a tuple with the DecisionScore field value
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetDecisionScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DecisionScore, true
}

// SetDecisionScore sets field value
func (o *DecisionResponse) SetDecisionScore(v float32) {
	o.DecisionScore = v
}

// GetFraudScore returns the FraudScore field value if set, zero value otherwise.
func (o *DecisionResponse) GetFraudScore() FraudScore {
	if o == nil || IsNil(o.FraudScore) {
		var ret FraudScore
		return ret
	}
	return *o.FraudScore
}

// GetFraudScoreOk returns a tuple with the FraudScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetFraudScoreOk() (*FraudScore, bool) {
	if o == nil || IsNil(o.FraudScore) {
		return nil, false
	}
	return o.FraudScore, true
}

// HasFraudScore returns a boolean if a field has been set.
func (o *DecisionResponse) HasFraudScore() bool {
	if o != nil && !IsNil(o.FraudScore) {
		return true
	}

	return false
}

// SetFraudScore gets a reference to the given FraudScore and assigns it to the FraudScore field.
func (o *DecisionResponse) SetFraudScore(v FraudScore) {
	o.FraudScore = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *DecisionResponse) GetBreakdown() RiskBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret RiskBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetBreakdownOk() (*RiskBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *DecisionResponse) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given RiskBreakdown and assigns it to the Breakdown field.
func (o *DecisionResponse) SetBreakdown(v RiskBreakdown) {
	o.Breakdown = &v
}

// GetReasonCodes returns the ReasonCodes field value if set, zero value otherwise.
func (o *DecisionResponse) GetReasonCodes() []string {
	if o == nil || IsNil(o.ReasonCodes) {
		var ret []string
		return ret
	}
	return o.ReasonCodes
}

// GetReasonCodesOk returns a tuple with the ReasonCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetReasonCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.ReasonCodes) {
		return nil, false
	}
	return o.ReasonCodes, true
}

// HasReasonCodes returns a boolean if a field has been set.
func (o *DecisionResponse) HasReasonCodes() bool {
	if o != nil && !IsNil(o.ReasonCodes) {
		return true
	}

	return false
}

// SetReasonCodes gets a reference to the given []string and assigns it to the ReasonCodes field.
func (o *DecisionResponse) SetReasonCodes(v []string) {
	o.ReasonCodes = v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *DecisionResponse) GetReasons() []ReasonDetail {
	if o == nil || IsNil(o.Reasons) {
		var ret []ReasonDetail
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetReasonsOk() ([]ReasonDetail, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *DecisionResponse) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []ReasonDetail and assigns it to the Reasons field.
func (o *DecisionResponse) SetReasons(v []ReasonDetail) {
	o.Reasons = v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *DecisionResponse) GetActions() []string {
	if o == nil || IsNil(o.Actions) {
		var ret []string
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetActionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *DecisionResponse) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []string and assigns it to the Actions field.
func (o *DecisionResponse) SetActions(v []string) {
	o.Actions = v
}

// GetPaymentIntentId returns the PaymentIntentId field value if set, zero value otherwise.
func (o *DecisionResponse) GetPaymentIntentId() string {
	if o == nil || IsNil(o.PaymentIntentId) {
		var ret string
		return ret
	}
	return *o.PaymentIntentId
}

// GetPaymentIntentIdOk returns a tuple with the PaymentIntentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetPaymentIntentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentIntentId) {
		return nil, false
	}
	return o.PaymentIntentId, true
}

// HasPaymentIntentId returns a boolean if a field has been set.
func (o *DecisionResponse) HasPaymentIntentId() bool {
	if o != nil && !IsNil(o.PaymentIntentId) {
		return true
	}

	return false
}

// SetPaymentIntentId gets a reference to the given string and assigns it to the PaymentIntentId field.
func (o *DecisionResponse) SetPaymentIntentId(v string) {
	o.PaymentIntentId = &v
}

// GetPolicyVersion returns the PolicyVersion field value if set, zero value otherwise.
func (o *DecisionResponse) GetPolicyVersion() string {
	if o == nil || IsNil(o.PolicyVersion) {
		var ret string
		return ret
	}
	return *o.PolicyVersion
}

// GetPolicyVersionOk returns a tuple with the PolicyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetPolicyVersionOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyVersion) {
		return nil, false
	}
	return o.PolicyVersion, true
}

// HasPolicyVersion returns a boolean if a field has been set.
func (o *DecisionResponse) HasPolicyVersion() bool {
	if o != nil && !IsNil(o.PolicyVersion) {
		return true
	}

	return false
}

// SetPolicyVersion gets a reference to the given string and assigns it to the PolicyVersion field.
func (o *DecisionResponse) SetPolicyVersion(v string) {
	o.PolicyVersion = &v
}

// GetModelVersion returns the ModelVersion field value if set, zero value otherwise.
func (o *DecisionResponse) GetModelVersion() string {
	if o == nil || IsNil(o.ModelVersion) {
		var ret string
		return ret
	}
	return *o.ModelVersion
}

// GetModelVersionOk returns a tuple with the ModelVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetModelVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ModelVersion) {
		return nil, false
	}
	return o.ModelVersion, true
}

// HasModelVersion returns a boolean if a field has been set.
func (o *DecisionResponse) HasModelVersion() bool {
	if o != nil && !IsNil(o.ModelVersion) {
		return true
	}

	return false
}

// SetModelVersion gets a reference to the given string and assigns it to the ModelVersion field.
func (o *DecisionResponse) SetModelVersion(v string) {
	o.ModelVersion = &v
}

// GetTtlSeconds returns the TtlSeconds field value if set, zero value otherwise.
func (o *DecisionResponse) GetTtlSeconds() int32 {
	if o == nil || IsNil(o.TtlSeconds) {
		var ret int32
		return ret
	}
	return *o.TtlSeconds
}

// GetTtlSecondsOk returns a tuple with the TtlSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResponse) GetTtlSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TtlSeconds) {
		return nil, false
	}
	return o.TtlSeconds, true
}

// HasTtlSeconds returns a boolean if a field has been set.
func (o *DecisionResponse) HasTtlSeconds() bool {
	if o != nil && !IsNil(o.TtlSeconds) {
		return true
	}

	return false
}

// SetTtlSeconds gets a reference to the given int32 and assigns it to the TtlSeconds field.
func (o *DecisionResponse) SetTtlSeconds(v int32) {
	o.TtlSeconds = &v
}

func (o DecisionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecisionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assessmentId"] = o.AssessmentId
	toSerialize["decision"] = o.Decision
	toSerialize["decisionAt"] = o.DecisionAt
	toSerialize["riskScore"] = o.RiskScore
	toSerialize["decisionScore"] = o.DecisionScore
	if !IsNil(o.FraudScore) {
		toSerialize["fraudScore"] = o.FraudScore
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	if !IsNil(o.ReasonCodes) {
		toSerialize["reasonCodes"] = o.ReasonCodes
	}
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.PaymentIntentId) {
		toSerialize["paymentIntentId"] = o.PaymentIntentId
	}
	if !IsNil(o.PolicyVersion) {
		toSerialize["policyVersion"] = o.PolicyVersion
	}
	if !IsNil(o.ModelVersion) {
		toSerialize["modelVersion"] = o.ModelVersion
	}
	if !IsNil(o.TtlSeconds) {
		toSerialize["ttlSeconds"] = o.TtlSeconds
	}
	return toSerialize, nil
}

func (o *DecisionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assessmentId",
		"decision",
		"decisionAt",
		"riskScore",
		"decisionScore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecisionResponse := _DecisionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDecisionResponse)

	if err != nil {
		return err
	}

	*o = DecisionResponse(varDecisionResponse)

	return err
}

type NullableDecisionResponse struct {
	value *DecisionResponse
	isSet bool
}

func (v NullableDecisionResponse) Get() *DecisionResponse {
	return v.value
}

func (v *NullableDecisionResponse) Set(val *DecisionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDecisionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDecisionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecisionResponse(val *DecisionResponse) *NullableDecisionResponse {
	return &NullableDecisionResponse{value: val, isSet: true}
}

func (v NullableDecisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecisionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


