/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PaymentCardTypeEnum The type of card used for the payment.
type PaymentCardTypeEnum string

// List of PaymentCardTypeEnum
const (
	PAYMENTCARDTYPEENUM_CREDIT PaymentCardTypeEnum = "credit"
	PAYMENTCARDTYPEENUM_DEBIT PaymentCardTypeEnum = "debit"
	PAYMENTCARDTYPEENUM_PREPAID PaymentCardTypeEnum = "prepaid"
)

// All allowed values of PaymentCardTypeEnum enum
var AllowedPaymentCardTypeEnumEnumValues = []PaymentCardTypeEnum{
	"credit",
	"debit",
	"prepaid",
}

func (v *PaymentCardTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentCardTypeEnum(value)
	for _, existing := range AllowedPaymentCardTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaymentCardTypeEnum", value)
}

// NewPaymentCardTypeEnumFromValue returns a pointer to a valid PaymentCardTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentCardTypeEnumFromValue(v string) (*PaymentCardTypeEnum, error) {
	ev := PaymentCardTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentCardTypeEnum: valid values are %v", v, AllowedPaymentCardTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentCardTypeEnum) IsValid() bool {
	for _, existing := range AllowedPaymentCardTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentCardTypeEnum value
func (v PaymentCardTypeEnum) Ptr() *PaymentCardTypeEnum {
	return &v
}

type NullablePaymentCardTypeEnum struct {
	value *PaymentCardTypeEnum
	isSet bool
}

func (v NullablePaymentCardTypeEnum) Get() *PaymentCardTypeEnum {
	return v.value
}

func (v *NullablePaymentCardTypeEnum) Set(val *PaymentCardTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentCardTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentCardTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentCardTypeEnum(val *PaymentCardTypeEnum) *NullablePaymentCardTypeEnum {
	return &NullablePaymentCardTypeEnum{value: val, isSet: true}
}

func (v NullablePaymentCardTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentCardTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

