/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.3
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SignalsRequest - Request for processing application workflow signals. Determined by `signalType`. 
type SignalsRequest struct {
	SignalsAccountVariant *SignalsAccountVariant
	SignalsInteractionVariant *SignalsInteractionVariant
}

// SignalsAccountVariantAsSignalsRequest is a convenience function that returns SignalsAccountVariant wrapped in SignalsRequest
func SignalsAccountVariantAsSignalsRequest(v *SignalsAccountVariant) SignalsRequest {
	return SignalsRequest{
		SignalsAccountVariant: v,
	}
}

// SignalsInteractionVariantAsSignalsRequest is a convenience function that returns SignalsInteractionVariant wrapped in SignalsRequest
func SignalsInteractionVariantAsSignalsRequest(v *SignalsInteractionVariant) SignalsRequest {
	return SignalsRequest{
		SignalsInteractionVariant: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SignalsRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SignalsAccountVariant
	err = newStrictDecoder(data).Decode(&dst.SignalsAccountVariant)
	if err == nil {
		jsonSignalsAccountVariant, _ := json.Marshal(dst.SignalsAccountVariant)
		if string(jsonSignalsAccountVariant) == "{}" { // empty struct
			dst.SignalsAccountVariant = nil
		} else {
			if err = validator.Validate(dst.SignalsAccountVariant); err != nil {
				dst.SignalsAccountVariant = nil
			} else {
				match++
			}
		}
	} else {
		dst.SignalsAccountVariant = nil
	}

	// try to unmarshal data into SignalsInteractionVariant
	err = newStrictDecoder(data).Decode(&dst.SignalsInteractionVariant)
	if err == nil {
		jsonSignalsInteractionVariant, _ := json.Marshal(dst.SignalsInteractionVariant)
		if string(jsonSignalsInteractionVariant) == "{}" { // empty struct
			dst.SignalsInteractionVariant = nil
		} else {
			if err = validator.Validate(dst.SignalsInteractionVariant); err != nil {
				dst.SignalsInteractionVariant = nil
			} else {
				match++
			}
		}
	} else {
		dst.SignalsInteractionVariant = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SignalsAccountVariant = nil
		dst.SignalsInteractionVariant = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SignalsRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SignalsRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SignalsRequest) MarshalJSON() ([]byte, error) {
	if src.SignalsAccountVariant != nil {
		return json.Marshal(&src.SignalsAccountVariant)
	}

	if src.SignalsInteractionVariant != nil {
		return json.Marshal(&src.SignalsInteractionVariant)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SignalsRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SignalsAccountVariant != nil {
		return obj.SignalsAccountVariant
	}

	if obj.SignalsInteractionVariant != nil {
		return obj.SignalsInteractionVariant
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SignalsRequest) GetActualInstanceValue() (interface{}) {
	if obj.SignalsAccountVariant != nil {
		return *obj.SignalsAccountVariant
	}

	if obj.SignalsInteractionVariant != nil {
		return *obj.SignalsInteractionVariant
	}

	// all schemas are nil
	return nil
}

type NullableSignalsRequest struct {
	value *SignalsRequest
	isSet bool
}

func (v NullableSignalsRequest) Get() *SignalsRequest {
	return v.value
}

func (v *NullableSignalsRequest) Set(val *SignalsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalsRequest(val *SignalsRequest) *NullableSignalsRequest {
	return &NullableSignalsRequest{value: val, isSet: true}
}

func (v NullableSignalsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


