/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PaymentEventType The type of payment lifecycle event.
type PaymentEventType string

// List of PaymentEventType
const (
	PAYMENTEVENTTYPE_AUTHORIZATION PaymentEventType = "authorization"
	PAYMENTEVENTTYPE_CAPTURE PaymentEventType = "capture"
	PAYMENTEVENTTYPE_SETTLEMENT PaymentEventType = "settlement"
	PAYMENTEVENTTYPE_REFUND PaymentEventType = "refund"
	PAYMENTEVENTTYPE_DISPUTE PaymentEventType = "dispute"
	PAYMENTEVENTTYPE_CHARGEBACK PaymentEventType = "chargeback"
	PAYMENTEVENTTYPE_CHARGEBACK_OUTCOME PaymentEventType = "chargeback_outcome"
)

// All allowed values of PaymentEventType enum
var AllowedPaymentEventTypeEnumValues = []PaymentEventType{
	"authorization",
	"capture",
	"settlement",
	"refund",
	"dispute",
	"chargeback",
	"chargeback_outcome",
}

func (v *PaymentEventType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentEventType(value)
	for _, existing := range AllowedPaymentEventTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaymentEventType", value)
}

// NewPaymentEventTypeFromValue returns a pointer to a valid PaymentEventType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentEventTypeFromValue(v string) (*PaymentEventType, error) {
	ev := PaymentEventType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentEventType: valid values are %v", v, AllowedPaymentEventTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentEventType) IsValid() bool {
	for _, existing := range AllowedPaymentEventTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentEventType value
func (v PaymentEventType) Ptr() *PaymentEventType {
	return &v
}

type NullablePaymentEventType struct {
	value *PaymentEventType
	isSet bool
}

func (v NullablePaymentEventType) Get() *PaymentEventType {
	return v.value
}

func (v *NullablePaymentEventType) Set(val *PaymentEventType) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentEventType) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentEventType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentEventType(val *PaymentEventType) *NullablePaymentEventType {
	return &NullablePaymentEventType{value: val, isSet: true}
}

func (v NullablePaymentEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentEventType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

