/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// CardNetworkEnum The type of card network.
type CardNetworkEnum string

// List of CardNetworkEnum
const (
	CARDNETWORKENUM_VISA CardNetworkEnum = "visa"
	CARDNETWORKENUM_MASTERCARD CardNetworkEnum = "mastercard"
	CARDNETWORKENUM_AMEX CardNetworkEnum = "amex"
	CARDNETWORKENUM_DISCOVER CardNetworkEnum = "discover"
	CARDNETWORKENUM_JCB CardNetworkEnum = "jcb"
	CARDNETWORKENUM_UNIONPAY CardNetworkEnum = "unionpay"
	CARDNETWORKENUM_OTHER CardNetworkEnum = "other"
)

// All allowed values of CardNetworkEnum enum
var AllowedCardNetworkEnumEnumValues = []CardNetworkEnum{
	"visa",
	"mastercard",
	"amex",
	"discover",
	"jcb",
	"unionpay",
	"other",
}

func (v *CardNetworkEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CardNetworkEnum(value)
	for _, existing := range AllowedCardNetworkEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CardNetworkEnum", value)
}

// NewCardNetworkEnumFromValue returns a pointer to a valid CardNetworkEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCardNetworkEnumFromValue(v string) (*CardNetworkEnum, error) {
	ev := CardNetworkEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CardNetworkEnum: valid values are %v", v, AllowedCardNetworkEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CardNetworkEnum) IsValid() bool {
	for _, existing := range AllowedCardNetworkEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CardNetworkEnum value
func (v CardNetworkEnum) Ptr() *CardNetworkEnum {
	return &v
}

type NullableCardNetworkEnum struct {
	value *CardNetworkEnum
	isSet bool
}

func (v NullableCardNetworkEnum) Get() *CardNetworkEnum {
	return v.value
}

func (v *NullableCardNetworkEnum) Set(val *CardNetworkEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCardNetworkEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCardNetworkEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardNetworkEnum(val *CardNetworkEnum) *NullableCardNetworkEnum {
	return &NullableCardNetworkEnum{value: val, isSet: true}
}

func (v NullableCardNetworkEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardNetworkEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
