/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.21
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReasonDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReasonDetail{}

// ReasonDetail Merchant-friendly detail for a specific risk reason.
type ReasonDetail struct {
	// Technical reason code (e.g., GEO_COUNTRY_SANCTIONED).
	Code string `json:"code"`
	Category RiskCategoryEnum `json:"category"`
	// Merchant-friendly name for the risk reason.
	DisplayName string `json:"displayName"`
	// Detailed explanation of the risk signal.
	Description *string `json:"description,omitempty"`
	// Suggested action for the merchant to mitigate this specific risk.
	RecommendedAction *string `json:"recommendedAction,omitempty"`
}

type _ReasonDetail ReasonDetail

// NewReasonDetail instantiates a new ReasonDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReasonDetail(code string, category RiskCategoryEnum, displayName string) *ReasonDetail {
	this := ReasonDetail{}
	this.Code = code
	this.Category = category
	this.DisplayName = displayName
	return &this
}

// NewReasonDetailWithDefaults instantiates a new ReasonDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReasonDetailWithDefaults() *ReasonDetail {
	this := ReasonDetail{}
	return &this
}

// GetCode returns the Code field value
func (o *ReasonDetail) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ReasonDetail) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ReasonDetail) SetCode(v string) {
	o.Code = v
}

// GetCategory returns the Category field value
func (o *ReasonDetail) GetCategory() RiskCategoryEnum {
	if o == nil {
		var ret RiskCategoryEnum
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ReasonDetail) GetCategoryOk() (*RiskCategoryEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ReasonDetail) SetCategory(v RiskCategoryEnum) {
	o.Category = v
}

// GetDisplayName returns the DisplayName field value
func (o *ReasonDetail) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ReasonDetail) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ReasonDetail) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ReasonDetail) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasonDetail) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ReasonDetail) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ReasonDetail) SetDescription(v string) {
	o.Description = &v
}

// GetRecommendedAction returns the RecommendedAction field value if set, zero value otherwise.
func (o *ReasonDetail) GetRecommendedAction() string {
	if o == nil || IsNil(o.RecommendedAction) {
		var ret string
		return ret
	}
	return *o.RecommendedAction
}

// GetRecommendedActionOk returns a tuple with the RecommendedAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReasonDetail) GetRecommendedActionOk() (*string, bool) {
	if o == nil || IsNil(o.RecommendedAction) {
		return nil, false
	}
	return o.RecommendedAction, true
}

// HasRecommendedAction returns a boolean if a field has been set.
func (o *ReasonDetail) HasRecommendedAction() bool {
	if o != nil && !IsNil(o.RecommendedAction) {
		return true
	}

	return false
}

// SetRecommendedAction gets a reference to the given string and assigns it to the RecommendedAction field.
func (o *ReasonDetail) SetRecommendedAction(v string) {
	o.RecommendedAction = &v
}

func (o ReasonDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReasonDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["category"] = o.Category
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RecommendedAction) {
		toSerialize["recommendedAction"] = o.RecommendedAction
	}
	return toSerialize, nil
}

func (o *ReasonDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"category",
		"displayName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReasonDetail := _ReasonDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReasonDetail)

	if err != nil {
		return err
	}

	*o = ReasonDetail(varReasonDetail)

	return err
}

type NullableReasonDetail struct {
	value *ReasonDetail
	isSet bool
}

func (v NullableReasonDetail) Get() *ReasonDetail {
	return v.value
}

func (v *NullableReasonDetail) Set(val *ReasonDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableReasonDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableReasonDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReasonDetail(val *ReasonDetail) *NullableReasonDetail {
	return &NullableReasonDetail{value: val, isSet: true}
}

func (v NullableReasonDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReasonDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


