/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the KycPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KycPayload{}

// KycPayload KYC provider result payload.
type KycPayload struct {
	Provider *string `json:"provider,omitempty"`
	// The document type used for verification.
	DocumentType *string `json:"documentType,omitempty"`
	Country *string `json:"country,omitempty"`
	// The result of the KYC check.
	Result *string `json:"result,omitempty"`
	// Array of reason codes for the KYC check.
	ReasonCodes []string `json:"reasonCodes,omitempty"`
	// Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
	Metadata *string `json:"metadata,omitempty"`
}

// NewKycPayload instantiates a new KycPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKycPayload() *KycPayload {
	this := KycPayload{}
	return &this
}

// NewKycPayloadWithDefaults instantiates a new KycPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKycPayloadWithDefaults() *KycPayload {
	this := KycPayload{}
	return &this
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *KycPayload) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *KycPayload) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *KycPayload) SetProvider(v string) {
	o.Provider = &v
}

// GetDocumentType returns the DocumentType field value if set, zero value otherwise.
func (o *KycPayload) GetDocumentType() string {
	if o == nil || IsNil(o.DocumentType) {
		var ret string
		return ret
	}
	return *o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetDocumentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentType) {
		return nil, false
	}
	return o.DocumentType, true
}

// HasDocumentType returns a boolean if a field has been set.
func (o *KycPayload) HasDocumentType() bool {
	if o != nil && !IsNil(o.DocumentType) {
		return true
	}

	return false
}

// SetDocumentType gets a reference to the given string and assigns it to the DocumentType field.
func (o *KycPayload) SetDocumentType(v string) {
	o.DocumentType = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *KycPayload) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *KycPayload) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *KycPayload) SetCountry(v string) {
	o.Country = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *KycPayload) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *KycPayload) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *KycPayload) SetResult(v string) {
	o.Result = &v
}

// GetReasonCodes returns the ReasonCodes field value if set, zero value otherwise.
func (o *KycPayload) GetReasonCodes() []string {
	if o == nil || IsNil(o.ReasonCodes) {
		var ret []string
		return ret
	}
	return o.ReasonCodes
}

// GetReasonCodesOk returns a tuple with the ReasonCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetReasonCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.ReasonCodes) {
		return nil, false
	}
	return o.ReasonCodes, true
}

// HasReasonCodes returns a boolean if a field has been set.
func (o *KycPayload) HasReasonCodes() bool {
	if o != nil && !IsNil(o.ReasonCodes) {
		return true
	}

	return false
}

// SetReasonCodes gets a reference to the given []string and assigns it to the ReasonCodes field.
func (o *KycPayload) SetReasonCodes(v []string) {
	o.ReasonCodes = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *KycPayload) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycPayload) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *KycPayload) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *KycPayload) SetMetadata(v string) {
	o.Metadata = &v
}

func (o KycPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KycPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.DocumentType) {
		toSerialize["documentType"] = o.DocumentType
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.ReasonCodes) {
		toSerialize["reasonCodes"] = o.ReasonCodes
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableKycPayload struct {
	value *KycPayload
	isSet bool
}

func (v NullableKycPayload) Get() *KycPayload {
	return v.value
}

func (v *NullableKycPayload) Set(val *KycPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableKycPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableKycPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKycPayload(val *KycPayload) *NullableKycPayload {
	return &NullableKycPayload{value: val, isSet: true}
}

func (v NullableKycPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKycPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


