/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the PaymentOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentOutcome{}

// PaymentOutcome Payment outcome details. Structured by lifecycle stage for clarity and validation. Stages include authorization, capture, refund, dispute, chargeback, and chargebackOutcome. 
type PaymentOutcome struct {
	Authorization *PaymentAuthorizationOutcome `json:"authorization,omitempty"`
	Capture *PaymentCaptureOutcome `json:"capture,omitempty"`
	Refund *PaymentRefundOutcome `json:"refund,omitempty"`
	Dispute *PaymentDisputeOutcome `json:"dispute,omitempty"`
	Chargeback *PaymentChargeback `json:"chargeback,omitempty"`
	ChargebackOutcome *PaymentChargebackOutcome `json:"chargebackOutcome,omitempty"`
}

// NewPaymentOutcome instantiates a new PaymentOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentOutcome() *PaymentOutcome {
	this := PaymentOutcome{}
	return &this
}

// NewPaymentOutcomeWithDefaults instantiates a new PaymentOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentOutcomeWithDefaults() *PaymentOutcome {
	this := PaymentOutcome{}
	return &this
}

// GetAuthorization returns the Authorization field value if set, zero value otherwise.
func (o *PaymentOutcome) GetAuthorization() PaymentAuthorizationOutcome {
	if o == nil || IsNil(o.Authorization) {
		var ret PaymentAuthorizationOutcome
		return ret
	}
	return *o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetAuthorizationOk() (*PaymentAuthorizationOutcome, bool) {
	if o == nil || IsNil(o.Authorization) {
		return nil, false
	}
	return o.Authorization, true
}

// HasAuthorization returns a boolean if a field has been set.
func (o *PaymentOutcome) HasAuthorization() bool {
	if o != nil && !IsNil(o.Authorization) {
		return true
	}

	return false
}

// SetAuthorization gets a reference to the given PaymentAuthorizationOutcome and assigns it to the Authorization field.
func (o *PaymentOutcome) SetAuthorization(v PaymentAuthorizationOutcome) {
	o.Authorization = &v
}

// GetCapture returns the Capture field value if set, zero value otherwise.
func (o *PaymentOutcome) GetCapture() PaymentCaptureOutcome {
	if o == nil || IsNil(o.Capture) {
		var ret PaymentCaptureOutcome
		return ret
	}
	return *o.Capture
}

// GetCaptureOk returns a tuple with the Capture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetCaptureOk() (*PaymentCaptureOutcome, bool) {
	if o == nil || IsNil(o.Capture) {
		return nil, false
	}
	return o.Capture, true
}

// HasCapture returns a boolean if a field has been set.
func (o *PaymentOutcome) HasCapture() bool {
	if o != nil && !IsNil(o.Capture) {
		return true
	}

	return false
}

// SetCapture gets a reference to the given PaymentCaptureOutcome and assigns it to the Capture field.
func (o *PaymentOutcome) SetCapture(v PaymentCaptureOutcome) {
	o.Capture = &v
}

// GetRefund returns the Refund field value if set, zero value otherwise.
func (o *PaymentOutcome) GetRefund() PaymentRefundOutcome {
	if o == nil || IsNil(o.Refund) {
		var ret PaymentRefundOutcome
		return ret
	}
	return *o.Refund
}

// GetRefundOk returns a tuple with the Refund field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetRefundOk() (*PaymentRefundOutcome, bool) {
	if o == nil || IsNil(o.Refund) {
		return nil, false
	}
	return o.Refund, true
}

// HasRefund returns a boolean if a field has been set.
func (o *PaymentOutcome) HasRefund() bool {
	if o != nil && !IsNil(o.Refund) {
		return true
	}

	return false
}

// SetRefund gets a reference to the given PaymentRefundOutcome and assigns it to the Refund field.
func (o *PaymentOutcome) SetRefund(v PaymentRefundOutcome) {
	o.Refund = &v
}

// GetDispute returns the Dispute field value if set, zero value otherwise.
func (o *PaymentOutcome) GetDispute() PaymentDisputeOutcome {
	if o == nil || IsNil(o.Dispute) {
		var ret PaymentDisputeOutcome
		return ret
	}
	return *o.Dispute
}

// GetDisputeOk returns a tuple with the Dispute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetDisputeOk() (*PaymentDisputeOutcome, bool) {
	if o == nil || IsNil(o.Dispute) {
		return nil, false
	}
	return o.Dispute, true
}

// HasDispute returns a boolean if a field has been set.
func (o *PaymentOutcome) HasDispute() bool {
	if o != nil && !IsNil(o.Dispute) {
		return true
	}

	return false
}

// SetDispute gets a reference to the given PaymentDisputeOutcome and assigns it to the Dispute field.
func (o *PaymentOutcome) SetDispute(v PaymentDisputeOutcome) {
	o.Dispute = &v
}

// GetChargeback returns the Chargeback field value if set, zero value otherwise.
func (o *PaymentOutcome) GetChargeback() PaymentChargeback {
	if o == nil || IsNil(o.Chargeback) {
		var ret PaymentChargeback
		return ret
	}
	return *o.Chargeback
}

// GetChargebackOk returns a tuple with the Chargeback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetChargebackOk() (*PaymentChargeback, bool) {
	if o == nil || IsNil(o.Chargeback) {
		return nil, false
	}
	return o.Chargeback, true
}

// HasChargeback returns a boolean if a field has been set.
func (o *PaymentOutcome) HasChargeback() bool {
	if o != nil && !IsNil(o.Chargeback) {
		return true
	}

	return false
}

// SetChargeback gets a reference to the given PaymentChargeback and assigns it to the Chargeback field.
func (o *PaymentOutcome) SetChargeback(v PaymentChargeback) {
	o.Chargeback = &v
}

// GetChargebackOutcome returns the ChargebackOutcome field value if set, zero value otherwise.
func (o *PaymentOutcome) GetChargebackOutcome() PaymentChargebackOutcome {
	if o == nil || IsNil(o.ChargebackOutcome) {
		var ret PaymentChargebackOutcome
		return ret
	}
	return *o.ChargebackOutcome
}

// GetChargebackOutcomeOk returns a tuple with the ChargebackOutcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOutcome) GetChargebackOutcomeOk() (*PaymentChargebackOutcome, bool) {
	if o == nil || IsNil(o.ChargebackOutcome) {
		return nil, false
	}
	return o.ChargebackOutcome, true
}

// HasChargebackOutcome returns a boolean if a field has been set.
func (o *PaymentOutcome) HasChargebackOutcome() bool {
	if o != nil && !IsNil(o.ChargebackOutcome) {
		return true
	}

	return false
}

// SetChargebackOutcome gets a reference to the given PaymentChargebackOutcome and assigns it to the ChargebackOutcome field.
func (o *PaymentOutcome) SetChargebackOutcome(v PaymentChargebackOutcome) {
	o.ChargebackOutcome = &v
}

func (o PaymentOutcome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authorization) {
		toSerialize["authorization"] = o.Authorization
	}
	if !IsNil(o.Capture) {
		toSerialize["capture"] = o.Capture
	}
	if !IsNil(o.Refund) {
		toSerialize["refund"] = o.Refund
	}
	if !IsNil(o.Dispute) {
		toSerialize["dispute"] = o.Dispute
	}
	if !IsNil(o.Chargeback) {
		toSerialize["chargeback"] = o.Chargeback
	}
	if !IsNil(o.ChargebackOutcome) {
		toSerialize["chargebackOutcome"] = o.ChargebackOutcome
	}
	return toSerialize, nil
}

type NullablePaymentOutcome struct {
	value *PaymentOutcome
	isSet bool
}

func (v NullablePaymentOutcome) Get() *PaymentOutcome {
	return v.value
}

func (v *NullablePaymentOutcome) Set(val *PaymentOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentOutcome(val *PaymentOutcome) *NullablePaymentOutcome {
	return &NullablePaymentOutcome{value: val, isSet: true}
}

func (v NullablePaymentOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


