/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the PaymentAuthorizationOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentAuthorizationOutcome{}

// PaymentAuthorizationOutcome Authorization outcome details.
type PaymentAuthorizationOutcome struct {
	// Indicates whether authorization was approved.
	Approved *bool `json:"approved,omitempty"`
	// Authorization response code.
	ResponseCode *string `json:"responseCode,omitempty"`
}

// NewPaymentAuthorizationOutcome instantiates a new PaymentAuthorizationOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentAuthorizationOutcome() *PaymentAuthorizationOutcome {
	this := PaymentAuthorizationOutcome{}
	return &this
}

// NewPaymentAuthorizationOutcomeWithDefaults instantiates a new PaymentAuthorizationOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentAuthorizationOutcomeWithDefaults() *PaymentAuthorizationOutcome {
	this := PaymentAuthorizationOutcome{}
	return &this
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *PaymentAuthorizationOutcome) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentAuthorizationOutcome) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *PaymentAuthorizationOutcome) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *PaymentAuthorizationOutcome) SetApproved(v bool) {
	o.Approved = &v
}

// GetResponseCode returns the ResponseCode field value if set, zero value otherwise.
func (o *PaymentAuthorizationOutcome) GetResponseCode() string {
	if o == nil || IsNil(o.ResponseCode) {
		var ret string
		return ret
	}
	return *o.ResponseCode
}

// GetResponseCodeOk returns a tuple with the ResponseCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentAuthorizationOutcome) GetResponseCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseCode) {
		return nil, false
	}
	return o.ResponseCode, true
}

// HasResponseCode returns a boolean if a field has been set.
func (o *PaymentAuthorizationOutcome) HasResponseCode() bool {
	if o != nil && !IsNil(o.ResponseCode) {
		return true
	}

	return false
}

// SetResponseCode gets a reference to the given string and assigns it to the ResponseCode field.
func (o *PaymentAuthorizationOutcome) SetResponseCode(v string) {
	o.ResponseCode = &v
}

func (o PaymentAuthorizationOutcome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentAuthorizationOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.ResponseCode) {
		toSerialize["responseCode"] = o.ResponseCode
	}
	return toSerialize, nil
}

type NullablePaymentAuthorizationOutcome struct {
	value *PaymentAuthorizationOutcome
	isSet bool
}

func (v NullablePaymentAuthorizationOutcome) Get() *PaymentAuthorizationOutcome {
	return v.value
}

func (v *NullablePaymentAuthorizationOutcome) Set(val *PaymentAuthorizationOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentAuthorizationOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentAuthorizationOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentAuthorizationOutcome(val *PaymentAuthorizationOutcome) *NullablePaymentAuthorizationOutcome {
	return &NullablePaymentAuthorizationOutcome{value: val, isSet: true}
}

func (v NullablePaymentAuthorizationOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentAuthorizationOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


