/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the PaymentChargebackOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentChargebackOutcome{}

// PaymentChargebackOutcome Final disposition of the chargeback after investigation/representment.
type PaymentChargebackOutcome struct {
	// Outcome of the chargeback case.
	Status *string `json:"status,omitempty"`
}

// NewPaymentChargebackOutcome instantiates a new PaymentChargebackOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentChargebackOutcome() *PaymentChargebackOutcome {
	this := PaymentChargebackOutcome{}
	return &this
}

// NewPaymentChargebackOutcomeWithDefaults instantiates a new PaymentChargebackOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentChargebackOutcomeWithDefaults() *PaymentChargebackOutcome {
	this := PaymentChargebackOutcome{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PaymentChargebackOutcome) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentChargebackOutcome) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentChargebackOutcome) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PaymentChargebackOutcome) SetStatus(v string) {
	o.Status = &v
}

func (o PaymentChargebackOutcome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentChargebackOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePaymentChargebackOutcome struct {
	value *PaymentChargebackOutcome
	isSet bool
}

func (v NullablePaymentChargebackOutcome) Get() *PaymentChargebackOutcome {
	return v.value
}

func (v *NullablePaymentChargebackOutcome) Set(val *PaymentChargebackOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentChargebackOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentChargebackOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentChargebackOutcome(val *PaymentChargebackOutcome) *NullablePaymentChargebackOutcome {
	return &NullablePaymentChargebackOutcome{value: val, isSet: true}
}

func (v NullablePaymentChargebackOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentChargebackOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


