/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.10
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KycCheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KycCheckRequest{}

// KycCheckRequest struct for KycCheckRequest
type KycCheckRequest struct {
	// The specific subtype of the KYC event.
	EventSubtype string `json:"eventSubtype"`
	Entities *EntityIds `json:"entities,omitempty"`
	Account Account `json:"account"`
	Kyc *KycPayload `json:"kyc,omitempty"`
}

type _KycCheckRequest KycCheckRequest

// NewKycCheckRequest instantiates a new KycCheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKycCheckRequest(eventSubtype string, account Account) *KycCheckRequest {
	this := KycCheckRequest{}
	this.EventSubtype = eventSubtype
	this.Account = account
	return &this
}

// NewKycCheckRequestWithDefaults instantiates a new KycCheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKycCheckRequestWithDefaults() *KycCheckRequest {
	this := KycCheckRequest{}
	return &this
}

// GetEventSubtype returns the EventSubtype field value
func (o *KycCheckRequest) GetEventSubtype() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventSubtype
}

// GetEventSubtypeOk returns a tuple with the EventSubtype field value
// and a boolean to check if the value has been set.
func (o *KycCheckRequest) GetEventSubtypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventSubtype, true
}

// SetEventSubtype sets field value
func (o *KycCheckRequest) SetEventSubtype(v string) {
	o.EventSubtype = v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *KycCheckRequest) GetEntities() EntityIds {
	if o == nil || IsNil(o.Entities) {
		var ret EntityIds
		return ret
	}
	return *o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycCheckRequest) GetEntitiesOk() (*EntityIds, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *KycCheckRequest) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given EntityIds and assigns it to the Entities field.
func (o *KycCheckRequest) SetEntities(v EntityIds) {
	o.Entities = &v
}

// GetAccount returns the Account field value
func (o *KycCheckRequest) GetAccount() Account {
	if o == nil {
		var ret Account
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *KycCheckRequest) GetAccountOk() (*Account, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *KycCheckRequest) SetAccount(v Account) {
	o.Account = v
}

// GetKyc returns the Kyc field value if set, zero value otherwise.
func (o *KycCheckRequest) GetKyc() KycPayload {
	if o == nil || IsNil(o.Kyc) {
		var ret KycPayload
		return ret
	}
	return *o.Kyc
}

// GetKycOk returns a tuple with the Kyc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KycCheckRequest) GetKycOk() (*KycPayload, bool) {
	if o == nil || IsNil(o.Kyc) {
		return nil, false
	}
	return o.Kyc, true
}

// HasKyc returns a boolean if a field has been set.
func (o *KycCheckRequest) HasKyc() bool {
	if o != nil && !IsNil(o.Kyc) {
		return true
	}

	return false
}

// SetKyc gets a reference to the given KycPayload and assigns it to the Kyc field.
func (o *KycCheckRequest) SetKyc(v KycPayload) {
	o.Kyc = &v
}

func (o KycCheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KycCheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventSubtype"] = o.EventSubtype
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	toSerialize["account"] = o.Account
	if !IsNil(o.Kyc) {
		toSerialize["kyc"] = o.Kyc
	}
	return toSerialize, nil
}

func (o *KycCheckRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventSubtype",
		"account",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKycCheckRequest := _KycCheckRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKycCheckRequest)

	if err != nil {
		return err
	}

	*o = KycCheckRequest(varKycCheckRequest)

	return err
}

type NullableKycCheckRequest struct {
	value *KycCheckRequest
	isSet bool
}

func (v NullableKycCheckRequest) Get() *KycCheckRequest {
	return v.value
}

func (v *NullableKycCheckRequest) Set(val *KycCheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKycCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKycCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKycCheckRequest(val *KycCheckRequest) *NullableKycCheckRequest {
	return &NullableKycCheckRequest{value: val, isSet: true}
}

func (v NullableKycCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKycCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


