/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.4
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LineItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LineItem{}

// LineItem Lightweight, fraud-relevant item context representing a single cart entry. Omits heavy marketing assets (images, HTML copy) to prioritize low-latency authorization. 
type LineItem struct {
	// Platform-agnostic line item or cart item identifier. Supports standard alphanumeric IDs, Fortress identifiers (li_...), and GraphQL GIDs (gid://shopify/LineItem/12345). 
	Id *string `json:"id,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.:\\/]{1,128}$"`
	// Merchant SKU, barcode, or variant identifier.
	Sku *string `json:"sku,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.]{1,64}$"`
	// Concise product or item title.
	Title string `json:"title"`
	Category *ItemCategoryEnum `json:"category,omitempty"`
	// Quantity of the item being purchased.
	Quantity int32 `json:"quantity"`
	// Price per unit in the order currency.
	UnitPrice float32 `json:"unitPrice"`
	// Optional gross line total (unitPrice * quantity) before item discounts.
	TotalAmount *float32 `json:"totalAmount,omitempty"`
	// Indicates whether this item is fulfilled digitally without physical delivery.
	IsDigital *bool `json:"isDigital,omitempty"`
	// Indicates whether this item is a cash-equivalent stored value card or code.
	IsGiftCard *bool `json:"isGiftCard,omitempty"`
	// Whether this item requires physical dispatch to a postal address.
	RequiresShipping *bool `json:"requiresShipping,omitempty"`
	// Brand or manufacturer name (used for high-value resale targeting).
	Brand *string `json:"brand,omitempty"`
	// Public HTTP/HTTPS URL of the product image for review consoles.
	ImageUrl *string `json:"imageUrl,omitempty"`
	// Flexible container for storefront-specific variant traits (e.g. size, color).
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _LineItem LineItem

// NewLineItem instantiates a new LineItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLineItem(title string, quantity int32, unitPrice float32) *LineItem {
	this := LineItem{}
	this.Title = title
	this.Quantity = quantity
	this.UnitPrice = unitPrice
	return &this
}

// NewLineItemWithDefaults instantiates a new LineItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLineItemWithDefaults() *LineItem {
	this := LineItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LineItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LineItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LineItem) SetId(v string) {
	o.Id = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *LineItem) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *LineItem) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *LineItem) SetSku(v string) {
	o.Sku = &v
}

// GetTitle returns the Title field value
func (o *LineItem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *LineItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *LineItem) SetTitle(v string) {
	o.Title = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *LineItem) GetCategory() ItemCategoryEnum {
	if o == nil || IsNil(o.Category) {
		var ret ItemCategoryEnum
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetCategoryOk() (*ItemCategoryEnum, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *LineItem) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given ItemCategoryEnum and assigns it to the Category field.
func (o *LineItem) SetCategory(v ItemCategoryEnum) {
	o.Category = &v
}

// GetQuantity returns the Quantity field value
func (o *LineItem) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *LineItem) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *LineItem) SetQuantity(v int32) {
	o.Quantity = v
}

// GetUnitPrice returns the UnitPrice field value
func (o *LineItem) GetUnitPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value
// and a boolean to check if the value has been set.
func (o *LineItem) GetUnitPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnitPrice, true
}

// SetUnitPrice sets field value
func (o *LineItem) SetUnitPrice(v float32) {
	o.UnitPrice = v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *LineItem) GetTotalAmount() float32 {
	if o == nil || IsNil(o.TotalAmount) {
		var ret float32
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetTotalAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *LineItem) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given float32 and assigns it to the TotalAmount field.
func (o *LineItem) SetTotalAmount(v float32) {
	o.TotalAmount = &v
}

// GetIsDigital returns the IsDigital field value if set, zero value otherwise.
func (o *LineItem) GetIsDigital() bool {
	if o == nil || IsNil(o.IsDigital) {
		var ret bool
		return ret
	}
	return *o.IsDigital
}

// GetIsDigitalOk returns a tuple with the IsDigital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetIsDigitalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDigital) {
		return nil, false
	}
	return o.IsDigital, true
}

// HasIsDigital returns a boolean if a field has been set.
func (o *LineItem) HasIsDigital() bool {
	if o != nil && !IsNil(o.IsDigital) {
		return true
	}

	return false
}

// SetIsDigital gets a reference to the given bool and assigns it to the IsDigital field.
func (o *LineItem) SetIsDigital(v bool) {
	o.IsDigital = &v
}

// GetIsGiftCard returns the IsGiftCard field value if set, zero value otherwise.
func (o *LineItem) GetIsGiftCard() bool {
	if o == nil || IsNil(o.IsGiftCard) {
		var ret bool
		return ret
	}
	return *o.IsGiftCard
}

// GetIsGiftCardOk returns a tuple with the IsGiftCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetIsGiftCardOk() (*bool, bool) {
	if o == nil || IsNil(o.IsGiftCard) {
		return nil, false
	}
	return o.IsGiftCard, true
}

// HasIsGiftCard returns a boolean if a field has been set.
func (o *LineItem) HasIsGiftCard() bool {
	if o != nil && !IsNil(o.IsGiftCard) {
		return true
	}

	return false
}

// SetIsGiftCard gets a reference to the given bool and assigns it to the IsGiftCard field.
func (o *LineItem) SetIsGiftCard(v bool) {
	o.IsGiftCard = &v
}

// GetRequiresShipping returns the RequiresShipping field value if set, zero value otherwise.
func (o *LineItem) GetRequiresShipping() bool {
	if o == nil || IsNil(o.RequiresShipping) {
		var ret bool
		return ret
	}
	return *o.RequiresShipping
}

// GetRequiresShippingOk returns a tuple with the RequiresShipping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetRequiresShippingOk() (*bool, bool) {
	if o == nil || IsNil(o.RequiresShipping) {
		return nil, false
	}
	return o.RequiresShipping, true
}

// HasRequiresShipping returns a boolean if a field has been set.
func (o *LineItem) HasRequiresShipping() bool {
	if o != nil && !IsNil(o.RequiresShipping) {
		return true
	}

	return false
}

// SetRequiresShipping gets a reference to the given bool and assigns it to the RequiresShipping field.
func (o *LineItem) SetRequiresShipping(v bool) {
	o.RequiresShipping = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *LineItem) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *LineItem) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *LineItem) SetBrand(v string) {
	o.Brand = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *LineItem) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *LineItem) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *LineItem) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *LineItem) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *LineItem) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *LineItem) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o LineItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LineItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	toSerialize["title"] = o.Title
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	toSerialize["quantity"] = o.Quantity
	toSerialize["unitPrice"] = o.UnitPrice
	if !IsNil(o.TotalAmount) {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if !IsNil(o.IsDigital) {
		toSerialize["isDigital"] = o.IsDigital
	}
	if !IsNil(o.IsGiftCard) {
		toSerialize["isGiftCard"] = o.IsGiftCard
	}
	if !IsNil(o.RequiresShipping) {
		toSerialize["requiresShipping"] = o.RequiresShipping
	}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *LineItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"quantity",
		"unitPrice",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLineItem := _LineItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLineItem)

	if err != nil {
		return err
	}

	*o = LineItem(varLineItem)

	return err
}

type NullableLineItem struct {
	value *LineItem
	isSet bool
}

func (v NullableLineItem) Get() *LineItem {
	return v.value
}

func (v *NullableLineItem) Set(val *LineItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLineItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLineItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLineItem(val *LineItem) *NullableLineItem {
	return &NullableLineItem{value: val, isSet: true}
}

func (v NullableLineItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLineItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


