/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.9
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// CardNetworkEnum The type of card network.
type CardNetworkEnum string

// List of CardNetworkEnum
const (
	CARDNETWORKENUM_VISA CardNetworkEnum = "visa"
	CARDNETWORKENUM_MASTERCARD CardNetworkEnum = "mastercard"
	CARDNETWORKENUM_AMEX CardNetworkEnum = "amex"
	CARDNETWORKENUM_DISCOVER CardNetworkEnum = "discover"
	CARDNETWORKENUM_JCB CardNetworkEnum = "jcb"
	CARDNETWORKENUM_UNIONPAY CardNetworkEnum = "unionpay"
	CARDNETWORKENUM_OTHER CardNetworkEnum = "other"
)

// All allowed values of CardNetworkEnum enum
var AllowedCardNetworkEnumEnumValues = []CardNetworkEnum{
	"visa",
	"mastercard",
	"amex",
	"discover",
	"jcb",
	"unionpay",
	"other",
}

func (v *CardNetworkEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CardNetworkEnum(value)
	for _, existing := range AllowedCardNetworkEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CardNetworkEnum", value)
}

// NewCardNetworkEnumFromValue returns a pointer to a valid CardNetworkEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCardNetworkEnumFromValue(v string) (*CardNetworkEnum, error) {
	ev := CardNetworkEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CardNetworkEnum: valid values are %v", v, AllowedCardNetworkEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CardNetworkEnum) IsValid() bool {
	for _, existing := range AllowedCardNetworkEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CardNetworkEnum value
func (v CardNetworkEnum) Ptr() *CardNetworkEnum {
	return &v
}

type NullableCardNetworkEnum struct {
	value *CardNetworkEnum
	isSet bool
}

func (v NullableCardNetworkEnum) Get() *CardNetworkEnum {
	return v.value
}

func (v *NullableCardNetworkEnum) Set(val *CardNetworkEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCardNetworkEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCardNetworkEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardNetworkEnum(val *CardNetworkEnum) *NullableCardNetworkEnum {
	return &NullableCardNetworkEnum{value: val, isSet: true}
}

func (v NullableCardNetworkEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardNetworkEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

