/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CategorySignal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategorySignal{}

// CategorySignal Risk analysis for a specific business category.
type CategorySignal struct {
	Level RiskLevelEnum `json:"level"`
	// Category-specific risk score (0.00 - 1.00).
	Score *float32 `json:"score,omitempty"`
	// Specific reason codes for this category.
	Reasons []string `json:"reasons,omitempty"`
	// Derived evidence and enrichment data for this category.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _CategorySignal CategorySignal

// NewCategorySignal instantiates a new CategorySignal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategorySignal(level RiskLevelEnum) *CategorySignal {
	this := CategorySignal{}
	this.Level = level
	return &this
}

// NewCategorySignalWithDefaults instantiates a new CategorySignal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategorySignalWithDefaults() *CategorySignal {
	this := CategorySignal{}
	return &this
}

// GetLevel returns the Level field value
func (o *CategorySignal) GetLevel() RiskLevelEnum {
	if o == nil {
		var ret RiskLevelEnum
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *CategorySignal) GetLevelOk() (*RiskLevelEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *CategorySignal) SetLevel(v RiskLevelEnum) {
	o.Level = v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *CategorySignal) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategorySignal) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *CategorySignal) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *CategorySignal) SetScore(v float32) {
	o.Score = &v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *CategorySignal) GetReasons() []string {
	if o == nil || IsNil(o.Reasons) {
		var ret []string
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategorySignal) GetReasonsOk() ([]string, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *CategorySignal) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []string and assigns it to the Reasons field.
func (o *CategorySignal) SetReasons(v []string) {
	o.Reasons = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CategorySignal) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategorySignal) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CategorySignal) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CategorySignal) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o CategorySignal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategorySignal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CategorySignal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategorySignal := _CategorySignal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategorySignal)

	if err != nil {
		return err
	}

	*o = CategorySignal(varCategorySignal)

	return err
}

type NullableCategorySignal struct {
	value *CategorySignal
	isSet bool
}

func (v NullableCategorySignal) Get() *CategorySignal {
	return v.value
}

func (v *NullableCategorySignal) Set(val *CategorySignal) {
	v.value = val
	v.isSet = true
}

func (v NullableCategorySignal) IsSet() bool {
	return v.isSet
}

func (v *NullableCategorySignal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategorySignal(val *CategorySignal) *NullableCategorySignal {
	return &NullableCategorySignal{value: val, isSet: true}
}

func (v NullableCategorySignal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategorySignal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


