/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// RiskCategoryEnum High-level business category for risk signals.
type RiskCategoryEnum string

// List of RiskCategoryEnum
const (
	RISKCATEGORYENUM_GEOGRAPHY RiskCategoryEnum = "geography"
	RISKCATEGORYENUM_IDENTITY RiskCategoryEnum = "identity"
	RISKCATEGORYENUM_BEHAVIOR RiskCategoryEnum = "behavior"
	RISKCATEGORYENUM_TRANSACTION RiskCategoryEnum = "transaction"
)

// All allowed values of RiskCategoryEnum enum
var AllowedRiskCategoryEnumEnumValues = []RiskCategoryEnum{
	"geography",
	"identity",
	"behavior",
	"transaction",
}

func (v *RiskCategoryEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RiskCategoryEnum(value)
	for _, existing := range AllowedRiskCategoryEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RiskCategoryEnum", value)
}

// NewRiskCategoryEnumFromValue returns a pointer to a valid RiskCategoryEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRiskCategoryEnumFromValue(v string) (*RiskCategoryEnum, error) {
	ev := RiskCategoryEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RiskCategoryEnum: valid values are %v", v, AllowedRiskCategoryEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RiskCategoryEnum) IsValid() bool {
	for _, existing := range AllowedRiskCategoryEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RiskCategoryEnum value
func (v RiskCategoryEnum) Ptr() *RiskCategoryEnum {
	return &v
}

type NullableRiskCategoryEnum struct {
	value *RiskCategoryEnum
	isSet bool
}

func (v NullableRiskCategoryEnum) Get() *RiskCategoryEnum {
	return v.value
}

func (v *NullableRiskCategoryEnum) Set(val *RiskCategoryEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskCategoryEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskCategoryEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskCategoryEnum(val *RiskCategoryEnum) *NullableRiskCategoryEnum {
	return &NullableRiskCategoryEnum{value: val, isSet: true}
}

func (v NullableRiskCategoryEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskCategoryEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

