/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.3
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Card type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Card{}

// Card struct for Card
type Card struct {
	// Fixed to `card` for this schema.
	Type string `json:"type"`
	CardNetwork *CardNetworkEnum `json:"cardNetwork,omitempty"`
	CardType *PaymentCardTypeEnum `json:"cardType,omitempty"`
	// Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN.
	Bin *string `json:"bin,omitempty" validate:"regexp=^[0-9]{6,8}$"`
	// ISO 3166-1 alpha-2 country code.
	IssuerCountry *string `json:"issuerCountry,omitempty" validate:"regexp=^[A-Z]{2}$"`
	AvsResult *AvsResultEnum `json:"avsResult,omitempty"`
	CvvResult *CvvResultEnum `json:"cvvResult,omitempty"`
	ScaMethod *ScaMethodEnum `json:"scaMethod,omitempty"`
	ThreeDS *ThreeDSData `json:"threeDS,omitempty"`
}

type _Card Card

// NewCard instantiates a new Card object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCard(type_ string) *Card {
	this := Card{}
	this.Type = type_
	return &this
}

// NewCardWithDefaults instantiates a new Card object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardWithDefaults() *Card {
	this := Card{}
	return &this
}

// GetType returns the Type field value
func (o *Card) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Card) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Card) SetType(v string) {
	o.Type = v
}

// GetCardNetwork returns the CardNetwork field value if set, zero value otherwise.
func (o *Card) GetCardNetwork() CardNetworkEnum {
	if o == nil || IsNil(o.CardNetwork) {
		var ret CardNetworkEnum
		return ret
	}
	return *o.CardNetwork
}

// GetCardNetworkOk returns a tuple with the CardNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetCardNetworkOk() (*CardNetworkEnum, bool) {
	if o == nil || IsNil(o.CardNetwork) {
		return nil, false
	}
	return o.CardNetwork, true
}

// HasCardNetwork returns a boolean if a field has been set.
func (o *Card) HasCardNetwork() bool {
	if o != nil && !IsNil(o.CardNetwork) {
		return true
	}

	return false
}

// SetCardNetwork gets a reference to the given CardNetworkEnum and assigns it to the CardNetwork field.
func (o *Card) SetCardNetwork(v CardNetworkEnum) {
	o.CardNetwork = &v
}

// GetCardType returns the CardType field value if set, zero value otherwise.
func (o *Card) GetCardType() PaymentCardTypeEnum {
	if o == nil || IsNil(o.CardType) {
		var ret PaymentCardTypeEnum
		return ret
	}
	return *o.CardType
}

// GetCardTypeOk returns a tuple with the CardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetCardTypeOk() (*PaymentCardTypeEnum, bool) {
	if o == nil || IsNil(o.CardType) {
		return nil, false
	}
	return o.CardType, true
}

// HasCardType returns a boolean if a field has been set.
func (o *Card) HasCardType() bool {
	if o != nil && !IsNil(o.CardType) {
		return true
	}

	return false
}

// SetCardType gets a reference to the given PaymentCardTypeEnum and assigns it to the CardType field.
func (o *Card) SetCardType(v PaymentCardTypeEnum) {
	o.CardType = &v
}

// GetBin returns the Bin field value if set, zero value otherwise.
func (o *Card) GetBin() string {
	if o == nil || IsNil(o.Bin) {
		var ret string
		return ret
	}
	return *o.Bin
}

// GetBinOk returns a tuple with the Bin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetBinOk() (*string, bool) {
	if o == nil || IsNil(o.Bin) {
		return nil, false
	}
	return o.Bin, true
}

// HasBin returns a boolean if a field has been set.
func (o *Card) HasBin() bool {
	if o != nil && !IsNil(o.Bin) {
		return true
	}

	return false
}

// SetBin gets a reference to the given string and assigns it to the Bin field.
func (o *Card) SetBin(v string) {
	o.Bin = &v
}

// GetIssuerCountry returns the IssuerCountry field value if set, zero value otherwise.
func (o *Card) GetIssuerCountry() string {
	if o == nil || IsNil(o.IssuerCountry) {
		var ret string
		return ret
	}
	return *o.IssuerCountry
}

// GetIssuerCountryOk returns a tuple with the IssuerCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetIssuerCountryOk() (*string, bool) {
	if o == nil || IsNil(o.IssuerCountry) {
		return nil, false
	}
	return o.IssuerCountry, true
}

// HasIssuerCountry returns a boolean if a field has been set.
func (o *Card) HasIssuerCountry() bool {
	if o != nil && !IsNil(o.IssuerCountry) {
		return true
	}

	return false
}

// SetIssuerCountry gets a reference to the given string and assigns it to the IssuerCountry field.
func (o *Card) SetIssuerCountry(v string) {
	o.IssuerCountry = &v
}

// GetAvsResult returns the AvsResult field value if set, zero value otherwise.
func (o *Card) GetAvsResult() AvsResultEnum {
	if o == nil || IsNil(o.AvsResult) {
		var ret AvsResultEnum
		return ret
	}
	return *o.AvsResult
}

// GetAvsResultOk returns a tuple with the AvsResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetAvsResultOk() (*AvsResultEnum, bool) {
	if o == nil || IsNil(o.AvsResult) {
		return nil, false
	}
	return o.AvsResult, true
}

// HasAvsResult returns a boolean if a field has been set.
func (o *Card) HasAvsResult() bool {
	if o != nil && !IsNil(o.AvsResult) {
		return true
	}

	return false
}

// SetAvsResult gets a reference to the given AvsResultEnum and assigns it to the AvsResult field.
func (o *Card) SetAvsResult(v AvsResultEnum) {
	o.AvsResult = &v
}

// GetCvvResult returns the CvvResult field value if set, zero value otherwise.
func (o *Card) GetCvvResult() CvvResultEnum {
	if o == nil || IsNil(o.CvvResult) {
		var ret CvvResultEnum
		return ret
	}
	return *o.CvvResult
}

// GetCvvResultOk returns a tuple with the CvvResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetCvvResultOk() (*CvvResultEnum, bool) {
	if o == nil || IsNil(o.CvvResult) {
		return nil, false
	}
	return o.CvvResult, true
}

// HasCvvResult returns a boolean if a field has been set.
func (o *Card) HasCvvResult() bool {
	if o != nil && !IsNil(o.CvvResult) {
		return true
	}

	return false
}

// SetCvvResult gets a reference to the given CvvResultEnum and assigns it to the CvvResult field.
func (o *Card) SetCvvResult(v CvvResultEnum) {
	o.CvvResult = &v
}

// GetScaMethod returns the ScaMethod field value if set, zero value otherwise.
func (o *Card) GetScaMethod() ScaMethodEnum {
	if o == nil || IsNil(o.ScaMethod) {
		var ret ScaMethodEnum
		return ret
	}
	return *o.ScaMethod
}

// GetScaMethodOk returns a tuple with the ScaMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetScaMethodOk() (*ScaMethodEnum, bool) {
	if o == nil || IsNil(o.ScaMethod) {
		return nil, false
	}
	return o.ScaMethod, true
}

// HasScaMethod returns a boolean if a field has been set.
func (o *Card) HasScaMethod() bool {
	if o != nil && !IsNil(o.ScaMethod) {
		return true
	}

	return false
}

// SetScaMethod gets a reference to the given ScaMethodEnum and assigns it to the ScaMethod field.
func (o *Card) SetScaMethod(v ScaMethodEnum) {
	o.ScaMethod = &v
}

// GetThreeDS returns the ThreeDS field value if set, zero value otherwise.
func (o *Card) GetThreeDS() ThreeDSData {
	if o == nil || IsNil(o.ThreeDS) {
		var ret ThreeDSData
		return ret
	}
	return *o.ThreeDS
}

// GetThreeDSOk returns a tuple with the ThreeDS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Card) GetThreeDSOk() (*ThreeDSData, bool) {
	if o == nil || IsNil(o.ThreeDS) {
		return nil, false
	}
	return o.ThreeDS, true
}

// HasThreeDS returns a boolean if a field has been set.
func (o *Card) HasThreeDS() bool {
	if o != nil && !IsNil(o.ThreeDS) {
		return true
	}

	return false
}

// SetThreeDS gets a reference to the given ThreeDSData and assigns it to the ThreeDS field.
func (o *Card) SetThreeDS(v ThreeDSData) {
	o.ThreeDS = &v
}

func (o Card) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Card) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.CardNetwork) {
		toSerialize["cardNetwork"] = o.CardNetwork
	}
	if !IsNil(o.CardType) {
		toSerialize["cardType"] = o.CardType
	}
	if !IsNil(o.Bin) {
		toSerialize["bin"] = o.Bin
	}
	if !IsNil(o.IssuerCountry) {
		toSerialize["issuerCountry"] = o.IssuerCountry
	}
	if !IsNil(o.AvsResult) {
		toSerialize["avsResult"] = o.AvsResult
	}
	if !IsNil(o.CvvResult) {
		toSerialize["cvvResult"] = o.CvvResult
	}
	if !IsNil(o.ScaMethod) {
		toSerialize["scaMethod"] = o.ScaMethod
	}
	if !IsNil(o.ThreeDS) {
		toSerialize["threeDS"] = o.ThreeDS
	}
	return toSerialize, nil
}

func (o *Card) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCard := _Card{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCard)

	if err != nil {
		return err
	}

	*o = Card(varCard)

	return err
}

type NullableCard struct {
	value *Card
	isSet bool
}

func (v NullableCard) Get() *Card {
	return v.value
}

func (v *NullableCard) Set(val *Card) {
	v.value = val
	v.isSet = true
}

func (v NullableCard) IsSet() bool {
	return v.isSet
}

func (v *NullableCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCard(val *Card) *NullableCard {
	return &NullableCard{value: val, isSet: true}
}

func (v NullableCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


