/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PaymentRealtimeTypeEnum The type of real-time payment network used.
type PaymentRealtimeTypeEnum string

// List of PaymentRealtimeTypeEnum
const (
	PAYMENTREALTIMETYPEENUM_ZELLE PaymentRealtimeTypeEnum = "zelle"
	PAYMENTREALTIMETYPEENUM_RTP PaymentRealtimeTypeEnum = "rtp"
	PAYMENTREALTIMETYPEENUM_FED_NOW PaymentRealtimeTypeEnum = "fed_now"
	PAYMENTREALTIMETYPEENUM_FASTER_PAYMENTS PaymentRealtimeTypeEnum = "faster_payments"
	PAYMENTREALTIMETYPEENUM_UPI PaymentRealtimeTypeEnum = "upi"
)

// All allowed values of PaymentRealtimeTypeEnum enum
var AllowedPaymentRealtimeTypeEnumEnumValues = []PaymentRealtimeTypeEnum{
	"zelle",
	"rtp",
	"fed_now",
	"faster_payments",
	"upi",
}

func (v *PaymentRealtimeTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentRealtimeTypeEnum(value)
	for _, existing := range AllowedPaymentRealtimeTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaymentRealtimeTypeEnum", value)
}

// NewPaymentRealtimeTypeEnumFromValue returns a pointer to a valid PaymentRealtimeTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentRealtimeTypeEnumFromValue(v string) (*PaymentRealtimeTypeEnum, error) {
	ev := PaymentRealtimeTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentRealtimeTypeEnum: valid values are %v", v, AllowedPaymentRealtimeTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentRealtimeTypeEnum) IsValid() bool {
	for _, existing := range AllowedPaymentRealtimeTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentRealtimeTypeEnum value
func (v PaymentRealtimeTypeEnum) Ptr() *PaymentRealtimeTypeEnum {
	return &v
}

type NullablePaymentRealtimeTypeEnum struct {
	value *PaymentRealtimeTypeEnum
	isSet bool
}

func (v NullablePaymentRealtimeTypeEnum) Get() *PaymentRealtimeTypeEnum {
	return v.value
}

func (v *NullablePaymentRealtimeTypeEnum) Set(val *PaymentRealtimeTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRealtimeTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRealtimeTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRealtimeTypeEnum(val *PaymentRealtimeTypeEnum) *NullablePaymentRealtimeTypeEnum {
	return &NullablePaymentRealtimeTypeEnum{value: val, isSet: true}
}

func (v NullablePaymentRealtimeTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRealtimeTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

