/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PaymentWalletTypeEnum The type of digital wallet used for the payment.
type PaymentWalletTypeEnum string

// List of PaymentWalletTypeEnum
const (
	PAYMENTWALLETTYPEENUM_PAYPAL PaymentWalletTypeEnum = "paypal"
	PAYMENTWALLETTYPEENUM_APPLE_PAY PaymentWalletTypeEnum = "apple_pay"
	PAYMENTWALLETTYPEENUM_GOOGLE_PAY PaymentWalletTypeEnum = "google_pay"
	PAYMENTWALLETTYPEENUM_CASH_APP PaymentWalletTypeEnum = "cash_app"
	PAYMENTWALLETTYPEENUM_VENMO PaymentWalletTypeEnum = "venmo"
	PAYMENTWALLETTYPEENUM_LINK PaymentWalletTypeEnum = "link"
	PAYMENTWALLETTYPEENUM_SHOP_PAY PaymentWalletTypeEnum = "shop_pay"
	PAYMENTWALLETTYPEENUM_AMAZON_PAY PaymentWalletTypeEnum = "amazon_pay"
	PAYMENTWALLETTYPEENUM_SAMSUNG_PAY PaymentWalletTypeEnum = "samsung_pay"
	PAYMENTWALLETTYPEENUM_OTHER PaymentWalletTypeEnum = "other"
)

// All allowed values of PaymentWalletTypeEnum enum
var AllowedPaymentWalletTypeEnumEnumValues = []PaymentWalletTypeEnum{
	"paypal",
	"apple_pay",
	"google_pay",
	"cash_app",
	"venmo",
	"link",
	"shop_pay",
	"amazon_pay",
	"samsung_pay",
	"other",
}

func (v *PaymentWalletTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentWalletTypeEnum(value)
	for _, existing := range AllowedPaymentWalletTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaymentWalletTypeEnum", value)
}

// NewPaymentWalletTypeEnumFromValue returns a pointer to a valid PaymentWalletTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentWalletTypeEnumFromValue(v string) (*PaymentWalletTypeEnum, error) {
	ev := PaymentWalletTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentWalletTypeEnum: valid values are %v", v, AllowedPaymentWalletTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentWalletTypeEnum) IsValid() bool {
	for _, existing := range AllowedPaymentWalletTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentWalletTypeEnum value
func (v PaymentWalletTypeEnum) Ptr() *PaymentWalletTypeEnum {
	return &v
}

type NullablePaymentWalletTypeEnum struct {
	value *PaymentWalletTypeEnum
	isSet bool
}

func (v NullablePaymentWalletTypeEnum) Get() *PaymentWalletTypeEnum {
	return v.value
}

func (v *NullablePaymentWalletTypeEnum) Set(val *PaymentWalletTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentWalletTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentWalletTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentWalletTypeEnum(val *PaymentWalletTypeEnum) *NullablePaymentWalletTypeEnum {
	return &NullablePaymentWalletTypeEnum{value: val, isSet: true}
}

func (v NullablePaymentWalletTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentWalletTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

