/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PaymentWalletTypeEnum The type of digital wallet used for the payment.
type PaymentWalletTypeEnum string

// List of PaymentWalletTypeEnum
const (
	PAYMENTWALLETTYPEENUM_PAYPAL PaymentWalletTypeEnum = "paypal"
	PAYMENTWALLETTYPEENUM_APPLE_PAY PaymentWalletTypeEnum = "apple_pay"
	PAYMENTWALLETTYPEENUM_GOOGLE_PAY PaymentWalletTypeEnum = "google_pay"
	PAYMENTWALLETTYPEENUM_CASH_APP PaymentWalletTypeEnum = "cash_app"
	PAYMENTWALLETTYPEENUM_VENMO PaymentWalletTypeEnum = "venmo"
)

// All allowed values of PaymentWalletTypeEnum enum
var AllowedPaymentWalletTypeEnumEnumValues = []PaymentWalletTypeEnum{
	"paypal",
	"apple_pay",
	"google_pay",
	"cash_app",
	"venmo",
}

func (v *PaymentWalletTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentWalletTypeEnum(value)
	for _, existing := range AllowedPaymentWalletTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaymentWalletTypeEnum", value)
}

// NewPaymentWalletTypeEnumFromValue returns a pointer to a valid PaymentWalletTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentWalletTypeEnumFromValue(v string) (*PaymentWalletTypeEnum, error) {
	ev := PaymentWalletTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentWalletTypeEnum: valid values are %v", v, AllowedPaymentWalletTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentWalletTypeEnum) IsValid() bool {
	for _, existing := range AllowedPaymentWalletTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentWalletTypeEnum value
func (v PaymentWalletTypeEnum) Ptr() *PaymentWalletTypeEnum {
	return &v
}

type NullablePaymentWalletTypeEnum struct {
	value *PaymentWalletTypeEnum
	isSet bool
}

func (v NullablePaymentWalletTypeEnum) Get() *PaymentWalletTypeEnum {
	return v.value
}

func (v *NullablePaymentWalletTypeEnum) Set(val *PaymentWalletTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentWalletTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentWalletTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentWalletTypeEnum(val *PaymentWalletTypeEnum) *NullablePaymentWalletTypeEnum {
	return &NullablePaymentWalletTypeEnum{value: val, isSet: true}
}

func (v NullablePaymentWalletTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentWalletTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

