/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.21
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignalsAccountVariant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalsAccountVariant{}

// SignalsAccountVariant Account-level signal variant (single account state snapshot).
type SignalsAccountVariant struct {
	// Value for account signals.
	SignalType string `json:"signalType"`
	Entities EntityIds `json:"entities"`
	Account Account `json:"account"`
}

type _SignalsAccountVariant SignalsAccountVariant

// NewSignalsAccountVariant instantiates a new SignalsAccountVariant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalsAccountVariant(signalType string, entities EntityIds, account Account) *SignalsAccountVariant {
	this := SignalsAccountVariant{}
	this.SignalType = signalType
	this.Entities = entities
	this.Account = account
	return &this
}

// NewSignalsAccountVariantWithDefaults instantiates a new SignalsAccountVariant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalsAccountVariantWithDefaults() *SignalsAccountVariant {
	this := SignalsAccountVariant{}
	return &this
}

// GetSignalType returns the SignalType field value
func (o *SignalsAccountVariant) GetSignalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalType
}

// GetSignalTypeOk returns a tuple with the SignalType field value
// and a boolean to check if the value has been set.
func (o *SignalsAccountVariant) GetSignalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalType, true
}

// SetSignalType sets field value
func (o *SignalsAccountVariant) SetSignalType(v string) {
	o.SignalType = v
}

// GetEntities returns the Entities field value
func (o *SignalsAccountVariant) GetEntities() EntityIds {
	if o == nil {
		var ret EntityIds
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *SignalsAccountVariant) GetEntitiesOk() (*EntityIds, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entities, true
}

// SetEntities sets field value
func (o *SignalsAccountVariant) SetEntities(v EntityIds) {
	o.Entities = v
}

// GetAccount returns the Account field value
func (o *SignalsAccountVariant) GetAccount() Account {
	if o == nil {
		var ret Account
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *SignalsAccountVariant) GetAccountOk() (*Account, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *SignalsAccountVariant) SetAccount(v Account) {
	o.Account = v
}

func (o SignalsAccountVariant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalsAccountVariant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signalType"] = o.SignalType
	toSerialize["entities"] = o.Entities
	toSerialize["account"] = o.Account
	return toSerialize, nil
}

func (o *SignalsAccountVariant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signalType",
		"entities",
		"account",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignalsAccountVariant := _SignalsAccountVariant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignalsAccountVariant)

	if err != nil {
		return err
	}

	*o = SignalsAccountVariant(varSignalsAccountVariant)

	return err
}

type NullableSignalsAccountVariant struct {
	value *SignalsAccountVariant
	isSet bool
}

func (v NullableSignalsAccountVariant) Get() *SignalsAccountVariant {
	return v.value
}

func (v *NullableSignalsAccountVariant) Set(val *SignalsAccountVariant) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalsAccountVariant) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalsAccountVariant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalsAccountVariant(val *SignalsAccountVariant) *NullableSignalsAccountVariant {
	return &NullableSignalsAccountVariant{value: val, isSet: true}
}

func (v NullableSignalsAccountVariant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalsAccountVariant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


