/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FraudScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FraudScore{}

// FraudScore Fraud score for a specific transaction or entity.
type FraudScore struct {
	RiskLevel RiskLevelEnum `json:"riskLevel"`
	Confidence *ConfidenceEnum `json:"confidence,omitempty"`
	// Fraud risk score (0.00 - 1.00).
	Score *float32 `json:"score,omitempty"`
	// A human-readable explanation of the fraud score, if available.
	Explanation *string `json:"explanation,omitempty"`
}

type _FraudScore FraudScore

// NewFraudScore instantiates a new FraudScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFraudScore(riskLevel RiskLevelEnum) *FraudScore {
	this := FraudScore{}
	this.RiskLevel = riskLevel
	return &this
}

// NewFraudScoreWithDefaults instantiates a new FraudScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFraudScoreWithDefaults() *FraudScore {
	this := FraudScore{}
	return &this
}

// GetRiskLevel returns the RiskLevel field value
func (o *FraudScore) GetRiskLevel() RiskLevelEnum {
	if o == nil {
		var ret RiskLevelEnum
		return ret
	}

	return o.RiskLevel
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value
// and a boolean to check if the value has been set.
func (o *FraudScore) GetRiskLevelOk() (*RiskLevelEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskLevel, true
}

// SetRiskLevel sets field value
func (o *FraudScore) SetRiskLevel(v RiskLevelEnum) {
	o.RiskLevel = v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *FraudScore) GetConfidence() ConfidenceEnum {
	if o == nil || IsNil(o.Confidence) {
		var ret ConfidenceEnum
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudScore) GetConfidenceOk() (*ConfidenceEnum, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *FraudScore) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given ConfidenceEnum and assigns it to the Confidence field.
func (o *FraudScore) SetConfidence(v ConfidenceEnum) {
	o.Confidence = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *FraudScore) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudScore) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *FraudScore) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *FraudScore) SetScore(v float32) {
	o.Score = &v
}

// GetExplanation returns the Explanation field value if set, zero value otherwise.
func (o *FraudScore) GetExplanation() string {
	if o == nil || IsNil(o.Explanation) {
		var ret string
		return ret
	}
	return *o.Explanation
}

// GetExplanationOk returns a tuple with the Explanation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudScore) GetExplanationOk() (*string, bool) {
	if o == nil || IsNil(o.Explanation) {
		return nil, false
	}
	return o.Explanation, true
}

// HasExplanation returns a boolean if a field has been set.
func (o *FraudScore) HasExplanation() bool {
	if o != nil && !IsNil(o.Explanation) {
		return true
	}

	return false
}

// SetExplanation gets a reference to the given string and assigns it to the Explanation field.
func (o *FraudScore) SetExplanation(v string) {
	o.Explanation = &v
}

func (o FraudScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FraudScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["riskLevel"] = o.RiskLevel
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.Explanation) {
		toSerialize["explanation"] = o.Explanation
	}
	return toSerialize, nil
}

func (o *FraudScore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"riskLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFraudScore := _FraudScore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFraudScore)

	if err != nil {
		return err
	}

	*o = FraudScore(varFraudScore)

	return err
}

type NullableFraudScore struct {
	value *FraudScore
	isSet bool
}

func (v NullableFraudScore) Get() *FraudScore {
	return v.value
}

func (v *NullableFraudScore) Set(val *FraudScore) {
	v.value = val
	v.isSet = true
}

func (v NullableFraudScore) IsSet() bool {
	return v.isSet
}

func (v *NullableFraudScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFraudScore(val *FraudScore) *NullableFraudScore {
	return &NullableFraudScore{value: val, isSet: true}
}

func (v NullableFraudScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFraudScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


