/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.4
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// ItemCategoryEnum Standardized high-level commodity classification for fraud scoring.
type ItemCategoryEnum string

// List of ItemCategoryEnum
const (
	ITEMCATEGORYENUM_PHYSICAL ItemCategoryEnum = "physical"
	ITEMCATEGORYENUM_DIGITAL_CONTENT ItemCategoryEnum = "digital_content"
	ITEMCATEGORYENUM_GIFT_CARD ItemCategoryEnum = "gift_card"
	ITEMCATEGORYENUM_SUBSCRIPTION ItemCategoryEnum = "subscription"
	ITEMCATEGORYENUM_SERVICE ItemCategoryEnum = "service"
	ITEMCATEGORYENUM_TRAVEL ItemCategoryEnum = "travel"
	ITEMCATEGORYENUM_CRYPTO_VOUCHER ItemCategoryEnum = "crypto_voucher"
	ITEMCATEGORYENUM_OTHER ItemCategoryEnum = "other"
)

// All allowed values of ItemCategoryEnum enum
var AllowedItemCategoryEnumEnumValues = []ItemCategoryEnum{
	"physical",
	"digital_content",
	"gift_card",
	"subscription",
	"service",
	"travel",
	"crypto_voucher",
	"other",
}

func (v *ItemCategoryEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ItemCategoryEnum(value)
	for _, existing := range AllowedItemCategoryEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ItemCategoryEnum", value)
}

// NewItemCategoryEnumFromValue returns a pointer to a valid ItemCategoryEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewItemCategoryEnumFromValue(v string) (*ItemCategoryEnum, error) {
	ev := ItemCategoryEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ItemCategoryEnum: valid values are %v", v, AllowedItemCategoryEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ItemCategoryEnum) IsValid() bool {
	for _, existing := range AllowedItemCategoryEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ItemCategoryEnum value
func (v ItemCategoryEnum) Ptr() *ItemCategoryEnum {
	return &v
}

type NullableItemCategoryEnum struct {
	value *ItemCategoryEnum
	isSet bool
}

func (v NullableItemCategoryEnum) Get() *ItemCategoryEnum {
	return v.value
}

func (v *NullableItemCategoryEnum) Set(val *ItemCategoryEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableItemCategoryEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableItemCategoryEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemCategoryEnum(val *ItemCategoryEnum) *NullableItemCategoryEnum {
	return &NullableItemCategoryEnum{value: val, isSet: true}
}

func (v NullableItemCategoryEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemCategoryEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

