/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.1
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the ThreeDSData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreeDSData{}

// ThreeDSData 3D Secure (3DS) data for card transactions.
type ThreeDSData struct {
	// The version of the 3D Secure protocol used (e.g., '2.2.0').
	Version *string `json:"version,omitempty"`
	// Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication. 
	Eci *string `json:"eci,omitempty"`
	// The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged. 
	Flow *string `json:"flow,omitempty"`
	// Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false). 
	LiabilityShift *bool `json:"liabilityShift,omitempty"`
	// Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message. 
	CavvPresent *bool `json:"cavvPresent,omitempty"`
}

// NewThreeDSData instantiates a new ThreeDSData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreeDSData() *ThreeDSData {
	this := ThreeDSData{}
	return &this
}

// NewThreeDSDataWithDefaults instantiates a new ThreeDSData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreeDSDataWithDefaults() *ThreeDSData {
	this := ThreeDSData{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ThreeDSData) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreeDSData) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ThreeDSData) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ThreeDSData) SetVersion(v string) {
	o.Version = &v
}

// GetEci returns the Eci field value if set, zero value otherwise.
func (o *ThreeDSData) GetEci() string {
	if o == nil || IsNil(o.Eci) {
		var ret string
		return ret
	}
	return *o.Eci
}

// GetEciOk returns a tuple with the Eci field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreeDSData) GetEciOk() (*string, bool) {
	if o == nil || IsNil(o.Eci) {
		return nil, false
	}
	return o.Eci, true
}

// HasEci returns a boolean if a field has been set.
func (o *ThreeDSData) HasEci() bool {
	if o != nil && !IsNil(o.Eci) {
		return true
	}

	return false
}

// SetEci gets a reference to the given string and assigns it to the Eci field.
func (o *ThreeDSData) SetEci(v string) {
	o.Eci = &v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *ThreeDSData) GetFlow() string {
	if o == nil || IsNil(o.Flow) {
		var ret string
		return ret
	}
	return *o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreeDSData) GetFlowOk() (*string, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *ThreeDSData) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given string and assigns it to the Flow field.
func (o *ThreeDSData) SetFlow(v string) {
	o.Flow = &v
}

// GetLiabilityShift returns the LiabilityShift field value if set, zero value otherwise.
func (o *ThreeDSData) GetLiabilityShift() bool {
	if o == nil || IsNil(o.LiabilityShift) {
		var ret bool
		return ret
	}
	return *o.LiabilityShift
}

// GetLiabilityShiftOk returns a tuple with the LiabilityShift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreeDSData) GetLiabilityShiftOk() (*bool, bool) {
	if o == nil || IsNil(o.LiabilityShift) {
		return nil, false
	}
	return o.LiabilityShift, true
}

// HasLiabilityShift returns a boolean if a field has been set.
func (o *ThreeDSData) HasLiabilityShift() bool {
	if o != nil && !IsNil(o.LiabilityShift) {
		return true
	}

	return false
}

// SetLiabilityShift gets a reference to the given bool and assigns it to the LiabilityShift field.
func (o *ThreeDSData) SetLiabilityShift(v bool) {
	o.LiabilityShift = &v
}

// GetCavvPresent returns the CavvPresent field value if set, zero value otherwise.
func (o *ThreeDSData) GetCavvPresent() bool {
	if o == nil || IsNil(o.CavvPresent) {
		var ret bool
		return ret
	}
	return *o.CavvPresent
}

// GetCavvPresentOk returns a tuple with the CavvPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreeDSData) GetCavvPresentOk() (*bool, bool) {
	if o == nil || IsNil(o.CavvPresent) {
		return nil, false
	}
	return o.CavvPresent, true
}

// HasCavvPresent returns a boolean if a field has been set.
func (o *ThreeDSData) HasCavvPresent() bool {
	if o != nil && !IsNil(o.CavvPresent) {
		return true
	}

	return false
}

// SetCavvPresent gets a reference to the given bool and assigns it to the CavvPresent field.
func (o *ThreeDSData) SetCavvPresent(v bool) {
	o.CavvPresent = &v
}

func (o ThreeDSData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreeDSData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Eci) {
		toSerialize["eci"] = o.Eci
	}
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	if !IsNil(o.LiabilityShift) {
		toSerialize["liabilityShift"] = o.LiabilityShift
	}
	if !IsNil(o.CavvPresent) {
		toSerialize["cavvPresent"] = o.CavvPresent
	}
	return toSerialize, nil
}

type NullableThreeDSData struct {
	value *ThreeDSData
	isSet bool
}

func (v NullableThreeDSData) Get() *ThreeDSData {
	return v.value
}

func (v *NullableThreeDSData) Set(val *ThreeDSData) {
	v.value = val
	v.isSet = true
}

func (v NullableThreeDSData) IsSet() bool {
	return v.isSet
}

func (v *NullableThreeDSData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreeDSData(val *ThreeDSData) *NullableThreeDSData {
	return &NullableThreeDSData{value: val, isSet: true}
}

func (v NullableThreeDSData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreeDSData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


