/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.9
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// EntryMethodEnum The method used to capture card data.
type EntryMethodEnum string

// List of EntryMethodEnum
const (
	ENTRYMETHODENUM_CHIP EntryMethodEnum = "chip"
	ENTRYMETHODENUM_CONTACTLESS EntryMethodEnum = "contactless"
	ENTRYMETHODENUM_MAGSTRIPE EntryMethodEnum = "magstripe"
	ENTRYMETHODENUM_MANUAL_KEYED EntryMethodEnum = "manual_keyed"
	ENTRYMETHODENUM_CARD_ON_FILE EntryMethodEnum = "card_on_file"
	ENTRYMETHODENUM_WALLET_TOKEN EntryMethodEnum = "wallet_token"
	ENTRYMETHODENUM_NETWORK_TOKEN EntryMethodEnum = "network_token"
)

// All allowed values of EntryMethodEnum enum
var AllowedEntryMethodEnumEnumValues = []EntryMethodEnum{
	"chip",
	"contactless",
	"magstripe",
	"manual_keyed",
	"card_on_file",
	"wallet_token",
	"network_token",
}

func (v *EntryMethodEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EntryMethodEnum(value)
	for _, existing := range AllowedEntryMethodEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EntryMethodEnum", value)
}

// NewEntryMethodEnumFromValue returns a pointer to a valid EntryMethodEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEntryMethodEnumFromValue(v string) (*EntryMethodEnum, error) {
	ev := EntryMethodEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EntryMethodEnum: valid values are %v", v, AllowedEntryMethodEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EntryMethodEnum) IsValid() bool {
	for _, existing := range AllowedEntryMethodEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EntryMethodEnum value
func (v EntryMethodEnum) Ptr() *EntryMethodEnum {
	return &v
}

type NullableEntryMethodEnum struct {
	value *EntryMethodEnum
	isSet bool
}

func (v NullableEntryMethodEnum) Get() *EntryMethodEnum {
	return v.value
}

func (v *NullableEntryMethodEnum) Set(val *EntryMethodEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableEntryMethodEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableEntryMethodEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntryMethodEnum(val *EntryMethodEnum) *NullableEntryMethodEnum {
	return &NullableEntryMethodEnum{value: val, isSet: true}
}

func (v NullableEntryMethodEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntryMethodEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

