/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the StoredCredentialContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoredCredentialContext{}

// StoredCredentialContext Minimal stored-credential / recurrence context.
type StoredCredentialContext struct {
	Usage *PurchaseUsageEnum `json:"usage,omitempty"`
	Sequence *PurchaseSequenceEnum `json:"sequence,omitempty"`
	Initiator *PurchaseInitiatorEnum `json:"initiator,omitempty"`
}

// NewStoredCredentialContext instantiates a new StoredCredentialContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoredCredentialContext() *StoredCredentialContext {
	this := StoredCredentialContext{}
	var usage PurchaseUsageEnum = PURCHASEUSAGEENUM_ONE_TIME
	this.Usage = &usage
	return &this
}

// NewStoredCredentialContextWithDefaults instantiates a new StoredCredentialContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoredCredentialContextWithDefaults() *StoredCredentialContext {
	this := StoredCredentialContext{}
	var usage PurchaseUsageEnum = PURCHASEUSAGEENUM_ONE_TIME
	this.Usage = &usage
	return &this
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *StoredCredentialContext) GetUsage() PurchaseUsageEnum {
	if o == nil || IsNil(o.Usage) {
		var ret PurchaseUsageEnum
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoredCredentialContext) GetUsageOk() (*PurchaseUsageEnum, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *StoredCredentialContext) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given PurchaseUsageEnum and assigns it to the Usage field.
func (o *StoredCredentialContext) SetUsage(v PurchaseUsageEnum) {
	o.Usage = &v
}

// GetSequence returns the Sequence field value if set, zero value otherwise.
func (o *StoredCredentialContext) GetSequence() PurchaseSequenceEnum {
	if o == nil || IsNil(o.Sequence) {
		var ret PurchaseSequenceEnum
		return ret
	}
	return *o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoredCredentialContext) GetSequenceOk() (*PurchaseSequenceEnum, bool) {
	if o == nil || IsNil(o.Sequence) {
		return nil, false
	}
	return o.Sequence, true
}

// HasSequence returns a boolean if a field has been set.
func (o *StoredCredentialContext) HasSequence() bool {
	if o != nil && !IsNil(o.Sequence) {
		return true
	}

	return false
}

// SetSequence gets a reference to the given PurchaseSequenceEnum and assigns it to the Sequence field.
func (o *StoredCredentialContext) SetSequence(v PurchaseSequenceEnum) {
	o.Sequence = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *StoredCredentialContext) GetInitiator() PurchaseInitiatorEnum {
	if o == nil || IsNil(o.Initiator) {
		var ret PurchaseInitiatorEnum
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoredCredentialContext) GetInitiatorOk() (*PurchaseInitiatorEnum, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *StoredCredentialContext) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given PurchaseInitiatorEnum and assigns it to the Initiator field.
func (o *StoredCredentialContext) SetInitiator(v PurchaseInitiatorEnum) {
	o.Initiator = &v
}

func (o StoredCredentialContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoredCredentialContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.Sequence) {
		toSerialize["sequence"] = o.Sequence
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

type NullableStoredCredentialContext struct {
	value *StoredCredentialContext
	isSet bool
}

func (v NullableStoredCredentialContext) Get() *StoredCredentialContext {
	return v.value
}

func (v *NullableStoredCredentialContext) Set(val *StoredCredentialContext) {
	v.value = val
	v.isSet = true
}

func (v NullableStoredCredentialContext) IsSet() bool {
	return v.isSet
}

func (v *NullableStoredCredentialContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoredCredentialContext(val *StoredCredentialContext) *NullableStoredCredentialContext {
	return &NullableStoredCredentialContext{value: val, isSet: true}
}

func (v NullableStoredCredentialContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoredCredentialContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


