/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.2
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignalsInteractionVariant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalsInteractionVariant{}

// SignalsInteractionVariant Interaction batch signal variant (one or more user interactions).
type SignalsInteractionVariant struct {
	// Value for interaction signals.
	SignalType string `json:"signalType"`
	Entities EntityIds `json:"entities"`
	// One or more interactions associated with the signal.
	Interactions []Interaction `json:"interactions"`
}

type _SignalsInteractionVariant SignalsInteractionVariant

// NewSignalsInteractionVariant instantiates a new SignalsInteractionVariant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalsInteractionVariant(signalType string, entities EntityIds, interactions []Interaction) *SignalsInteractionVariant {
	this := SignalsInteractionVariant{}
	this.SignalType = signalType
	this.Entities = entities
	this.Interactions = interactions
	return &this
}

// NewSignalsInteractionVariantWithDefaults instantiates a new SignalsInteractionVariant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalsInteractionVariantWithDefaults() *SignalsInteractionVariant {
	this := SignalsInteractionVariant{}
	return &this
}

// GetSignalType returns the SignalType field value
func (o *SignalsInteractionVariant) GetSignalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalType
}

// GetSignalTypeOk returns a tuple with the SignalType field value
// and a boolean to check if the value has been set.
func (o *SignalsInteractionVariant) GetSignalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalType, true
}

// SetSignalType sets field value
func (o *SignalsInteractionVariant) SetSignalType(v string) {
	o.SignalType = v
}

// GetEntities returns the Entities field value
func (o *SignalsInteractionVariant) GetEntities() EntityIds {
	if o == nil {
		var ret EntityIds
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *SignalsInteractionVariant) GetEntitiesOk() (*EntityIds, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entities, true
}

// SetEntities sets field value
func (o *SignalsInteractionVariant) SetEntities(v EntityIds) {
	o.Entities = v
}

// GetInteractions returns the Interactions field value
func (o *SignalsInteractionVariant) GetInteractions() []Interaction {
	if o == nil {
		var ret []Interaction
		return ret
	}

	return o.Interactions
}

// GetInteractionsOk returns a tuple with the Interactions field value
// and a boolean to check if the value has been set.
func (o *SignalsInteractionVariant) GetInteractionsOk() ([]Interaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Interactions, true
}

// SetInteractions sets field value
func (o *SignalsInteractionVariant) SetInteractions(v []Interaction) {
	o.Interactions = v
}

func (o SignalsInteractionVariant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalsInteractionVariant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signalType"] = o.SignalType
	toSerialize["entities"] = o.Entities
	toSerialize["interactions"] = o.Interactions
	return toSerialize, nil
}

func (o *SignalsInteractionVariant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signalType",
		"entities",
		"interactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignalsInteractionVariant := _SignalsInteractionVariant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignalsInteractionVariant)

	if err != nil {
		return err
	}

	*o = SignalsInteractionVariant(varSignalsInteractionVariant)

	return err
}

type NullableSignalsInteractionVariant struct {
	value *SignalsInteractionVariant
	isSet bool
}

func (v NullableSignalsInteractionVariant) Get() *SignalsInteractionVariant {
	return v.value
}

func (v *NullableSignalsInteractionVariant) Set(val *SignalsInteractionVariant) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalsInteractionVariant) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalsInteractionVariant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalsInteractionVariant(val *SignalsInteractionVariant) *NullableSignalsInteractionVariant {
	return &NullableSignalsInteractionVariant{value: val, isSet: true}
}

func (v NullableSignalsInteractionVariant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalsInteractionVariant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


