/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6-rc.2
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the MerchantContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantContext{}

// MerchantContext Merchant context for the purchase.
type MerchantContext struct {
	// Merchant Category Code (MCC) for the merchant.
	Mcc *string `json:"mcc,omitempty" validate:"regexp=^[0-9]{4}$"`
	// ISO 3166-1 alpha-2 country code.
	MerchantCountry *string `json:"merchantCountry,omitempty" validate:"regexp=^[A-Z]{2}$"`
}

// NewMerchantContext instantiates a new MerchantContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantContext() *MerchantContext {
	this := MerchantContext{}
	return &this
}

// NewMerchantContextWithDefaults instantiates a new MerchantContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantContextWithDefaults() *MerchantContext {
	this := MerchantContext{}
	return &this
}

// GetMcc returns the Mcc field value if set, zero value otherwise.
func (o *MerchantContext) GetMcc() string {
	if o == nil || IsNil(o.Mcc) {
		var ret string
		return ret
	}
	return *o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantContext) GetMccOk() (*string, bool) {
	if o == nil || IsNil(o.Mcc) {
		return nil, false
	}
	return o.Mcc, true
}

// HasMcc returns a boolean if a field has been set.
func (o *MerchantContext) HasMcc() bool {
	if o != nil && !IsNil(o.Mcc) {
		return true
	}

	return false
}

// SetMcc gets a reference to the given string and assigns it to the Mcc field.
func (o *MerchantContext) SetMcc(v string) {
	o.Mcc = &v
}

// GetMerchantCountry returns the MerchantCountry field value if set, zero value otherwise.
func (o *MerchantContext) GetMerchantCountry() string {
	if o == nil || IsNil(o.MerchantCountry) {
		var ret string
		return ret
	}
	return *o.MerchantCountry
}

// GetMerchantCountryOk returns a tuple with the MerchantCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantContext) GetMerchantCountryOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantCountry) {
		return nil, false
	}
	return o.MerchantCountry, true
}

// HasMerchantCountry returns a boolean if a field has been set.
func (o *MerchantContext) HasMerchantCountry() bool {
	if o != nil && !IsNil(o.MerchantCountry) {
		return true
	}

	return false
}

// SetMerchantCountry gets a reference to the given string and assigns it to the MerchantCountry field.
func (o *MerchantContext) SetMerchantCountry(v string) {
	o.MerchantCountry = &v
}

func (o MerchantContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mcc) {
		toSerialize["mcc"] = o.Mcc
	}
	if !IsNil(o.MerchantCountry) {
		toSerialize["merchantCountry"] = o.MerchantCountry
	}
	return toSerialize, nil
}

type NullableMerchantContext struct {
	value *MerchantContext
	isSet bool
}

func (v NullableMerchantContext) Get() *MerchantContext {
	return v.value
}

func (v *NullableMerchantContext) Set(val *MerchantContext) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantContext) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantContext(val *MerchantContext) *NullableMerchantContext {
	return &NullableMerchantContext{value: val, isSet: true}
}

func (v NullableMerchantContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


