/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.9
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the RiskBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskBreakdown{}

// RiskBreakdown Breakdown of risk signals by business category.
type RiskBreakdown struct {
	Geography *CategorySignal `json:"geography,omitempty"`
	Identity *CategorySignal `json:"identity,omitempty"`
	Behavior *CategorySignal `json:"behavior,omitempty"`
	Transaction *CategorySignal `json:"transaction,omitempty"`
	Network *CategorySignal `json:"network,omitempty"`
}

// NewRiskBreakdown instantiates a new RiskBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskBreakdown() *RiskBreakdown {
	this := RiskBreakdown{}
	return &this
}

// NewRiskBreakdownWithDefaults instantiates a new RiskBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskBreakdownWithDefaults() *RiskBreakdown {
	this := RiskBreakdown{}
	return &this
}

// GetGeography returns the Geography field value if set, zero value otherwise.
func (o *RiskBreakdown) GetGeography() CategorySignal {
	if o == nil || IsNil(o.Geography) {
		var ret CategorySignal
		return ret
	}
	return *o.Geography
}

// GetGeographyOk returns a tuple with the Geography field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskBreakdown) GetGeographyOk() (*CategorySignal, bool) {
	if o == nil || IsNil(o.Geography) {
		return nil, false
	}
	return o.Geography, true
}

// HasGeography returns a boolean if a field has been set.
func (o *RiskBreakdown) HasGeography() bool {
	if o != nil && !IsNil(o.Geography) {
		return true
	}

	return false
}

// SetGeography gets a reference to the given CategorySignal and assigns it to the Geography field.
func (o *RiskBreakdown) SetGeography(v CategorySignal) {
	o.Geography = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *RiskBreakdown) GetIdentity() CategorySignal {
	if o == nil || IsNil(o.Identity) {
		var ret CategorySignal
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskBreakdown) GetIdentityOk() (*CategorySignal, bool) {
	if o == nil || IsNil(o.Identity) {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *RiskBreakdown) HasIdentity() bool {
	if o != nil && !IsNil(o.Identity) {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given CategorySignal and assigns it to the Identity field.
func (o *RiskBreakdown) SetIdentity(v CategorySignal) {
	o.Identity = &v
}

// GetBehavior returns the Behavior field value if set, zero value otherwise.
func (o *RiskBreakdown) GetBehavior() CategorySignal {
	if o == nil || IsNil(o.Behavior) {
		var ret CategorySignal
		return ret
	}
	return *o.Behavior
}

// GetBehaviorOk returns a tuple with the Behavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskBreakdown) GetBehaviorOk() (*CategorySignal, bool) {
	if o == nil || IsNil(o.Behavior) {
		return nil, false
	}
	return o.Behavior, true
}

// HasBehavior returns a boolean if a field has been set.
func (o *RiskBreakdown) HasBehavior() bool {
	if o != nil && !IsNil(o.Behavior) {
		return true
	}

	return false
}

// SetBehavior gets a reference to the given CategorySignal and assigns it to the Behavior field.
func (o *RiskBreakdown) SetBehavior(v CategorySignal) {
	o.Behavior = &v
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *RiskBreakdown) GetTransaction() CategorySignal {
	if o == nil || IsNil(o.Transaction) {
		var ret CategorySignal
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskBreakdown) GetTransactionOk() (*CategorySignal, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *RiskBreakdown) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given CategorySignal and assigns it to the Transaction field.
func (o *RiskBreakdown) SetTransaction(v CategorySignal) {
	o.Transaction = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *RiskBreakdown) GetNetwork() CategorySignal {
	if o == nil || IsNil(o.Network) {
		var ret CategorySignal
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskBreakdown) GetNetworkOk() (*CategorySignal, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *RiskBreakdown) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given CategorySignal and assigns it to the Network field.
func (o *RiskBreakdown) SetNetwork(v CategorySignal) {
	o.Network = &v
}

func (o RiskBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Geography) {
		toSerialize["geography"] = o.Geography
	}
	if !IsNil(o.Identity) {
		toSerialize["identity"] = o.Identity
	}
	if !IsNil(o.Behavior) {
		toSerialize["behavior"] = o.Behavior
	}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableRiskBreakdown struct {
	value *RiskBreakdown
	isSet bool
}

func (v NullableRiskBreakdown) Get() *RiskBreakdown {
	return v.value
}

func (v *NullableRiskBreakdown) Set(val *RiskBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskBreakdown(val *RiskBreakdown) *NullableRiskBreakdown {
	return &NullableRiskBreakdown{value: val, isSet: true}
}

func (v NullableRiskBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


