/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DecisionResolutionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecisionResolutionRequest{}

// DecisionResolutionRequest struct for DecisionResolutionRequest
type DecisionResolutionRequest struct {
	// The business entity type being resolved.
	TargetType string `json:"targetType"`
	// The unique identifier of the target entity under review (e.g. pi_*).
	TargetId string `json:"targetId"`
	// The resolution action to apply to the target.
	Decision string `json:"decision"`
	Analyst DecisionResolutionRequestAnalyst `json:"analyst"`
	// The ML-feedback ground-truth reason classification.
	ResolutionReason string `json:"resolutionReason"`
	// Additional operational notes or reasoning for this resolution.
	Notes *string `json:"notes,omitempty"`
}

type _DecisionResolutionRequest DecisionResolutionRequest

// NewDecisionResolutionRequest instantiates a new DecisionResolutionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecisionResolutionRequest(targetType string, targetId string, decision string, analyst DecisionResolutionRequestAnalyst, resolutionReason string) *DecisionResolutionRequest {
	this := DecisionResolutionRequest{}
	this.TargetType = targetType
	this.TargetId = targetId
	this.Decision = decision
	this.Analyst = analyst
	this.ResolutionReason = resolutionReason
	return &this
}

// NewDecisionResolutionRequestWithDefaults instantiates a new DecisionResolutionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionResolutionRequestWithDefaults() *DecisionResolutionRequest {
	this := DecisionResolutionRequest{}
	return &this
}

// GetTargetType returns the TargetType field value
func (o *DecisionResolutionRequest) GetTargetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetType
}

// GetTargetTypeOk returns a tuple with the TargetType field value
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetTargetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetType, true
}

// SetTargetType sets field value
func (o *DecisionResolutionRequest) SetTargetType(v string) {
	o.TargetType = v
}

// GetTargetId returns the TargetId field value
func (o *DecisionResolutionRequest) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *DecisionResolutionRequest) SetTargetId(v string) {
	o.TargetId = v
}

// GetDecision returns the Decision field value
func (o *DecisionResolutionRequest) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *DecisionResolutionRequest) SetDecision(v string) {
	o.Decision = v
}

// GetAnalyst returns the Analyst field value
func (o *DecisionResolutionRequest) GetAnalyst() DecisionResolutionRequestAnalyst {
	if o == nil {
		var ret DecisionResolutionRequestAnalyst
		return ret
	}

	return o.Analyst
}

// GetAnalystOk returns a tuple with the Analyst field value
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetAnalystOk() (*DecisionResolutionRequestAnalyst, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Analyst, true
}

// SetAnalyst sets field value
func (o *DecisionResolutionRequest) SetAnalyst(v DecisionResolutionRequestAnalyst) {
	o.Analyst = v
}

// GetResolutionReason returns the ResolutionReason field value
func (o *DecisionResolutionRequest) GetResolutionReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolutionReason
}

// GetResolutionReasonOk returns a tuple with the ResolutionReason field value
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetResolutionReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolutionReason, true
}

// SetResolutionReason sets field value
func (o *DecisionResolutionRequest) SetResolutionReason(v string) {
	o.ResolutionReason = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *DecisionResolutionRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecisionResolutionRequest) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *DecisionResolutionRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *DecisionResolutionRequest) SetNotes(v string) {
	o.Notes = &v
}

func (o DecisionResolutionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecisionResolutionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targetType"] = o.TargetType
	toSerialize["targetId"] = o.TargetId
	toSerialize["decision"] = o.Decision
	toSerialize["analyst"] = o.Analyst
	toSerialize["resolutionReason"] = o.ResolutionReason
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

func (o *DecisionResolutionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targetType",
		"targetId",
		"decision",
		"analyst",
		"resolutionReason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecisionResolutionRequest := _DecisionResolutionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDecisionResolutionRequest)

	if err != nil {
		return err
	}

	*o = DecisionResolutionRequest(varDecisionResolutionRequest)

	return err
}

type NullableDecisionResolutionRequest struct {
	value *DecisionResolutionRequest
	isSet bool
}

func (v NullableDecisionResolutionRequest) Get() *DecisionResolutionRequest {
	return v.value
}

func (v *NullableDecisionResolutionRequest) Set(val *DecisionResolutionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDecisionResolutionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDecisionResolutionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecisionResolutionRequest(val *DecisionResolutionRequest) *NullableDecisionResolutionRequest {
	return &NullableDecisionResolutionRequest{value: val, isSet: true}
}

func (v NullableDecisionResolutionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecisionResolutionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


