/*
Alogram PayRisk Engine

Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 

API version: 0.2.8
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PurchaseSequenceEnum First transaction in the series vs a subsequent one.
type PurchaseSequenceEnum string

// List of PurchaseSequenceEnum
const (
	PURCHASESEQUENCEENUM_FIRST PurchaseSequenceEnum = "first"
	PURCHASESEQUENCEENUM_SUBSEQUENT PurchaseSequenceEnum = "subsequent"
)

// All allowed values of PurchaseSequenceEnum enum
var AllowedPurchaseSequenceEnumEnumValues = []PurchaseSequenceEnum{
	"first",
	"subsequent",
}

func (v *PurchaseSequenceEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PurchaseSequenceEnum(value)
	for _, existing := range AllowedPurchaseSequenceEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PurchaseSequenceEnum", value)
}

// NewPurchaseSequenceEnumFromValue returns a pointer to a valid PurchaseSequenceEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPurchaseSequenceEnumFromValue(v string) (*PurchaseSequenceEnum, error) {
	ev := PurchaseSequenceEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PurchaseSequenceEnum: valid values are %v", v, AllowedPurchaseSequenceEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PurchaseSequenceEnum) IsValid() bool {
	for _, existing := range AllowedPurchaseSequenceEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PurchaseSequenceEnum value
func (v PurchaseSequenceEnum) Ptr() *PurchaseSequenceEnum {
	return &v
}

type NullablePurchaseSequenceEnum struct {
	value *PurchaseSequenceEnum
	isSet bool
}

func (v NullablePurchaseSequenceEnum) Get() *PurchaseSequenceEnum {
	return v.value
}

func (v *NullablePurchaseSequenceEnum) Set(val *PurchaseSequenceEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseSequenceEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseSequenceEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseSequenceEnum(val *PurchaseSequenceEnum) *NullablePurchaseSequenceEnum {
	return &NullablePurchaseSequenceEnum{value: val, isSet: true}
}

func (v NullablePurchaseSequenceEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseSequenceEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

