/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.21
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
)

// PayerTypeEnum The type of payer (consumer or business).
type PayerTypeEnum string

// List of PayerTypeEnum
const (
	PAYERTYPEENUM_CONSUMER PayerTypeEnum = "consumer"
	PAYERTYPEENUM_BUSINESS PayerTypeEnum = "business"
)

// All allowed values of PayerTypeEnum enum
var AllowedPayerTypeEnumEnumValues = []PayerTypeEnum{
	"consumer",
	"business",
}

func (v *PayerTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PayerTypeEnum(value)
	for _, existing := range AllowedPayerTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PayerTypeEnum", value)
}

// NewPayerTypeEnumFromValue returns a pointer to a valid PayerTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPayerTypeEnumFromValue(v string) (*PayerTypeEnum, error) {
	ev := PayerTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PayerTypeEnum: valid values are %v", v, AllowedPayerTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PayerTypeEnum) IsValid() bool {
	for _, existing := range AllowedPayerTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PayerTypeEnum value
func (v PayerTypeEnum) Ptr() *PayerTypeEnum {
	return &v
}

type NullablePayerTypeEnum struct {
	value *PayerTypeEnum
	isSet bool
}

func (v NullablePayerTypeEnum) Get() *PayerTypeEnum {
	return v.value
}

func (v *NullablePayerTypeEnum) Set(val *PayerTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullablePayerTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullablePayerTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayerTypeEnum(val *PayerTypeEnum) *NullablePayerTypeEnum {
	return &NullablePayerTypeEnum{value: val, isSet: true}
}

func (v NullablePayerTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayerTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

