/*
Payments Risk API

API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 

API version: 0.1.6
Contact: support@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Realtime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Realtime{}

// Realtime struct for Realtime
type Realtime struct {
	// Fixed to `realtime` for this schema.
	Type string `json:"type"`
	RealtimeType *PaymentRealtimeTypeEnum `json:"realtimeType,omitempty"`
}

type _Realtime Realtime

// NewRealtime instantiates a new Realtime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealtime(type_ string) *Realtime {
	this := Realtime{}
	this.Type = type_
	return &this
}

// NewRealtimeWithDefaults instantiates a new Realtime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealtimeWithDefaults() *Realtime {
	this := Realtime{}
	return &this
}

// GetType returns the Type field value
func (o *Realtime) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Realtime) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Realtime) SetType(v string) {
	o.Type = v
}

// GetRealtimeType returns the RealtimeType field value if set, zero value otherwise.
func (o *Realtime) GetRealtimeType() PaymentRealtimeTypeEnum {
	if o == nil || IsNil(o.RealtimeType) {
		var ret PaymentRealtimeTypeEnum
		return ret
	}
	return *o.RealtimeType
}

// GetRealtimeTypeOk returns a tuple with the RealtimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Realtime) GetRealtimeTypeOk() (*PaymentRealtimeTypeEnum, bool) {
	if o == nil || IsNil(o.RealtimeType) {
		return nil, false
	}
	return o.RealtimeType, true
}

// HasRealtimeType returns a boolean if a field has been set.
func (o *Realtime) HasRealtimeType() bool {
	if o != nil && !IsNil(o.RealtimeType) {
		return true
	}

	return false
}

// SetRealtimeType gets a reference to the given PaymentRealtimeTypeEnum and assigns it to the RealtimeType field.
func (o *Realtime) SetRealtimeType(v PaymentRealtimeTypeEnum) {
	o.RealtimeType = &v
}

func (o Realtime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Realtime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.RealtimeType) {
		toSerialize["realtimeType"] = o.RealtimeType
	}
	return toSerialize, nil
}

func (o *Realtime) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRealtime := _Realtime{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRealtime)

	if err != nil {
		return err
	}

	*o = Realtime(varRealtime)

	return err
}

type NullableRealtime struct {
	value *Realtime
	isSet bool
}

func (v NullableRealtime) Get() *Realtime {
	return v.value
}

func (v *NullableRealtime) Set(val *Realtime) {
	v.value = val
	v.isSet = true
}

func (v NullableRealtime) IsSet() bool {
	return v.isSet
}

func (v *NullableRealtime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealtime(val *Realtime) *NullableRealtime {
	return &NullableRealtime{value: val, isSet: true}
}

func (v NullableRealtime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealtime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
