/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.3.2
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PaymentMethod - Union of instrument-specific payment details.
type PaymentMethod struct {
	BankTransfer *BankTransfer
	Card *Card
	Crypto *Crypto
	Invoice *Invoice
	Realtime *Realtime
	Wallet *Wallet
}

// BankTransferAsPaymentMethod is a convenience function that returns BankTransfer wrapped in PaymentMethod
func BankTransferAsPaymentMethod(v *BankTransfer) PaymentMethod {
	return PaymentMethod{
		BankTransfer: v,
	}
}

// CardAsPaymentMethod is a convenience function that returns Card wrapped in PaymentMethod
func CardAsPaymentMethod(v *Card) PaymentMethod {
	return PaymentMethod{
		Card: v,
	}
}

// CryptoAsPaymentMethod is a convenience function that returns Crypto wrapped in PaymentMethod
func CryptoAsPaymentMethod(v *Crypto) PaymentMethod {
	return PaymentMethod{
		Crypto: v,
	}
}

// InvoiceAsPaymentMethod is a convenience function that returns Invoice wrapped in PaymentMethod
func InvoiceAsPaymentMethod(v *Invoice) PaymentMethod {
	return PaymentMethod{
		Invoice: v,
	}
}

// RealtimeAsPaymentMethod is a convenience function that returns Realtime wrapped in PaymentMethod
func RealtimeAsPaymentMethod(v *Realtime) PaymentMethod {
	return PaymentMethod{
		Realtime: v,
	}
}

// WalletAsPaymentMethod is a convenience function that returns Wallet wrapped in PaymentMethod
func WalletAsPaymentMethod(v *Wallet) PaymentMethod {
	return PaymentMethod{
		Wallet: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PaymentMethod) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BankTransfer
	err = newStrictDecoder(data).Decode(&dst.BankTransfer)
	if err == nil {
		jsonBankTransfer, _ := json.Marshal(dst.BankTransfer)
		if string(jsonBankTransfer) == "{}" { // empty struct
			dst.BankTransfer = nil
		} else {
			if err = validator.Validate(dst.BankTransfer); err != nil {
				dst.BankTransfer = nil
			} else {
				match++
			}
		}
	} else {
		dst.BankTransfer = nil
	}

	// try to unmarshal data into Card
	err = newStrictDecoder(data).Decode(&dst.Card)
	if err == nil {
		jsonCard, _ := json.Marshal(dst.Card)
		if string(jsonCard) == "{}" { // empty struct
			dst.Card = nil
		} else {
			if err = validator.Validate(dst.Card); err != nil {
				dst.Card = nil
			} else {
				match++
			}
		}
	} else {
		dst.Card = nil
	}

	// try to unmarshal data into Crypto
	err = newStrictDecoder(data).Decode(&dst.Crypto)
	if err == nil {
		jsonCrypto, _ := json.Marshal(dst.Crypto)
		if string(jsonCrypto) == "{}" { // empty struct
			dst.Crypto = nil
		} else {
			if err = validator.Validate(dst.Crypto); err != nil {
				dst.Crypto = nil
			} else {
				match++
			}
		}
	} else {
		dst.Crypto = nil
	}

	// try to unmarshal data into Invoice
	err = newStrictDecoder(data).Decode(&dst.Invoice)
	if err == nil {
		jsonInvoice, _ := json.Marshal(dst.Invoice)
		if string(jsonInvoice) == "{}" { // empty struct
			dst.Invoice = nil
		} else {
			if err = validator.Validate(dst.Invoice); err != nil {
				dst.Invoice = nil
			} else {
				match++
			}
		}
	} else {
		dst.Invoice = nil
	}

	// try to unmarshal data into Realtime
	err = newStrictDecoder(data).Decode(&dst.Realtime)
	if err == nil {
		jsonRealtime, _ := json.Marshal(dst.Realtime)
		if string(jsonRealtime) == "{}" { // empty struct
			dst.Realtime = nil
		} else {
			if err = validator.Validate(dst.Realtime); err != nil {
				dst.Realtime = nil
			} else {
				match++
			}
		}
	} else {
		dst.Realtime = nil
	}

	// try to unmarshal data into Wallet
	err = newStrictDecoder(data).Decode(&dst.Wallet)
	if err == nil {
		jsonWallet, _ := json.Marshal(dst.Wallet)
		if string(jsonWallet) == "{}" { // empty struct
			dst.Wallet = nil
		} else {
			if err = validator.Validate(dst.Wallet); err != nil {
				dst.Wallet = nil
			} else {
				match++
			}
		}
	} else {
		dst.Wallet = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BankTransfer = nil
		dst.Card = nil
		dst.Crypto = nil
		dst.Invoice = nil
		dst.Realtime = nil
		dst.Wallet = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PaymentMethod)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PaymentMethod)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PaymentMethod) MarshalJSON() ([]byte, error) {
	if src.BankTransfer != nil {
		return json.Marshal(&src.BankTransfer)
	}

	if src.Card != nil {
		return json.Marshal(&src.Card)
	}

	if src.Crypto != nil {
		return json.Marshal(&src.Crypto)
	}

	if src.Invoice != nil {
		return json.Marshal(&src.Invoice)
	}

	if src.Realtime != nil {
		return json.Marshal(&src.Realtime)
	}

	if src.Wallet != nil {
		return json.Marshal(&src.Wallet)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PaymentMethod) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BankTransfer != nil {
		return obj.BankTransfer
	}

	if obj.Card != nil {
		return obj.Card
	}

	if obj.Crypto != nil {
		return obj.Crypto
	}

	if obj.Invoice != nil {
		return obj.Invoice
	}

	if obj.Realtime != nil {
		return obj.Realtime
	}

	if obj.Wallet != nil {
		return obj.Wallet
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PaymentMethod) GetActualInstanceValue() (interface{}) {
	if obj.BankTransfer != nil {
		return *obj.BankTransfer
	}

	if obj.Card != nil {
		return *obj.Card
	}

	if obj.Crypto != nil {
		return *obj.Crypto
	}

	if obj.Invoice != nil {
		return *obj.Invoice
	}

	if obj.Realtime != nil {
		return *obj.Realtime
	}

	if obj.Wallet != nil {
		return *obj.Wallet
	}

	// all schemas are nil
	return nil
}

type NullablePaymentMethod struct {
	value *PaymentMethod
	isSet bool
}

func (v NullablePaymentMethod) Get() *PaymentMethod {
	return v.value
}

func (v *NullablePaymentMethod) Set(val *PaymentMethod) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethod) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethod(val *PaymentMethod) *NullablePaymentMethod {
	return &NullablePaymentMethod{value: val, isSet: true}
}

func (v NullablePaymentMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


