/*
Alogram PayRisk Engine

Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 

API version: 0.2.23
Contact: packages@alogram.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payrisk_v1

import (
	"encoding/json"
)

// checks if the PaymentDisputeOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentDisputeOutcome{}

// PaymentDisputeOutcome Dispute lifecycle status for the transaction.
type PaymentDisputeOutcome struct {
	// Dispute status.
	Status *string `json:"status,omitempty"`
}

// NewPaymentDisputeOutcome instantiates a new PaymentDisputeOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentDisputeOutcome() *PaymentDisputeOutcome {
	this := PaymentDisputeOutcome{}
	return &this
}

// NewPaymentDisputeOutcomeWithDefaults instantiates a new PaymentDisputeOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentDisputeOutcomeWithDefaults() *PaymentDisputeOutcome {
	this := PaymentDisputeOutcome{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PaymentDisputeOutcome) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentDisputeOutcome) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentDisputeOutcome) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PaymentDisputeOutcome) SetStatus(v string) {
	o.Status = &v
}

func (o PaymentDisputeOutcome) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentDisputeOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePaymentDisputeOutcome struct {
	value *PaymentDisputeOutcome
	isSet bool
}

func (v NullablePaymentDisputeOutcome) Get() *PaymentDisputeOutcome {
	return v.value
}

func (v *NullablePaymentDisputeOutcome) Set(val *PaymentDisputeOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentDisputeOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentDisputeOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentDisputeOutcome(val *PaymentDisputeOutcome) *NullablePaymentDisputeOutcome {
	return &NullablePaymentDisputeOutcome{value: val, isSet: true}
}

func (v NullablePaymentDisputeOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentDisputeOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


